### ISSUE TITLE
Safari - sort filtering and search not working

### ISSUE THREAD

**Issue by sha-one** [relax/relax#102]
Trying admin/UI out in a few browsers and have noticed that sort, filtering, and search are not working (for example in Media).

I'm on safari: Version 9.0 (11601.1.56)

Works great in Chrome!

**Comment by magalhas** [comment]
We're gonna squash this bug (and all others) when we complete the refactoring into redux. A couple of weeks and we'll solve this, I guess :) Thank you for reporting

**Comment by bruno12mota** [comment]
I believe this is fixed now :+1:
