### ISSUE TITLE
Firefox - no content appearing in Admin/UI

### ISSUE THREAD

**Issue by sha-one** [relax/relax#103]
In firefox I can login to Admin/UI and switch between menu's but there is no content displayed in the body of any Admin page/area.

For example:

<img width="1318" alt="screenshot 2015-10-18 11 04 02" src="https://cloud.githubusercontent.com/assets/3371979/10563629/5563a756-7588-11e5-91d3-c7fce19faa83.png">

Firefox version: 40.0.3

**Comment by magalhas** [comment]
Duplicates #45
