### ISSUE TITLE
allow to edit users

### ISSUE THREAD

**Issue by magalhas** [relax/relax#104]
As of now `UserEditContainer` only allows to output data of a user. We need to change it to allow editing an user as well.

**Comment by bruno12mota** [comment]
We need to decide if we're going to re design the dashboard area or not. No point of doing this task before knowing that

**Comment by ivomiguelas** [comment]
@bruno12mota Now that we are redesigning the dashboard, is this still blocked?

**Comment by bruno12mota** [comment]
We can unblock as soon as we have the finished design
