### ISSUE TITLE
reorganize components folder

### ISSUE THREAD

**Issue by magalhas** [relax/relax#113]

**Comment by bruno12mota** [comment]
@magalhas what's else to organize?

**Comment by magalhas** [comment]
We need to get rid of `admin/panels` folder, it doesn't make sense with the current `containers` structure.

There may be some more cleaning to do. We should consider also moving `elements` out of `components` folder. They're way too special for being among all the other dumb components, don't you agree?

**Comment by bruno12mota** [comment]
Made it a review to check which components were even being used. Also took a look to each one to put them valid for eslint. I think it's a matter of having a name for the element now, and this would be closed. Don't see why the elements would be out of this folder
