### ISSUE TITLE
Form element

### ISSUE THREAD

**Issue by bruno12mota** [relax/relax#12]

**Comment by magalhas** [comment]
I would rather see a generic form component instead of a one specific for contact.

**Comment by bruno12mota** [comment]
You will always have to have a form element wrapper, which might accept input types and other components, all the input components would link data to the form, agree?

**Comment by magalhas** [comment]
Yes. That's the probably the best way for a form to behave. The form may have a custom endpoint, an e-mail address, or a schema that the user previously defined. The last one looks like the most appealing use case.

**Comment by bruno12mota** [comment]
Form schema option blocked by route restriction, there needs to be a way of tagging a schema as public writable.

Also missing success/fail message on form submit as well as enable buttons added inside forms to submit it (something to change on the button component itself maybe)

**Comment by bruno12mota** [comment]
#124
