### ISSUE TITLE
scroll with touchpad does not work inside components menu

### ISSUE THREAD

**Issue by magalhas** [relax/relax#131]
See title.

**Comment by magalhas** [comment]
This doesn't seem to be happening in the HEAD. Can someone else confirm this ( @ivomiguelas ) so that we can safely close this bug.

**Comment by bruno12mota** [comment]
Doesn't happen for me at least

**Comment by ivomiguelas** [comment]
Still not working for me. I plugged in a regular mouse and scrolling doesn't work with the wheel either!

**Comment by bruno12mota** [comment]
Really strange, will try to update the scroll lib we're using. Which chrome version are you using?

**Comment by bruno12mota** [comment]
Can't replicate in any browser I have. @ivomiguelas does the scrollbar appear when you over the menu ate least?

**Comment by ivomiguelas** [comment]
@bruno12mota No, not on the right click menu and not on the bottom "+" menu.

**Comment by yoyeung** [comment]
@bruno12mota i think they are talking about this menu.
<img width="462" alt="screen shot 2016-02-12 at 3 20 38 pm" src="https://cloud.githubusercontent.com/assets/451538/13001006/4c072988-d19c-11e5-90d6-3421e129546a.png">
Just need to update elements-meun/index.less 
change .ballon's style from overflow hidden to scroll.
It will be fixed.

**Comment by BoefAE** [comment]
So yeah I'm facing the same issue, trying to create new content > schema but I can't scroll with touchpad (macbook) or mouse

**Comment by bruno12mota** [comment]
This is fixed
