### ISSUE TITLE
Feature request: /admin/pages UI enhancement

### ISSUE THREAD

**Issue by bondden** [relax/relax#134]
![2015-11-10_18-12-07](https://cloud.githubusercontent.com/assets/5232392/11062511/a5d348e6-87d9-11e5-8b93-033711af9956.png)

**Comment by ivomiguelas** [comment]
Appreciate the great feedback @bondden. We'll give the Dashboard area some more love soon.

**Comment by bruno12mota** [comment]
Resolved with new admin design
