### ISSUE TITLE
Settings overrides per viewport

### ISSUE THREAD

**Issue by magalhas** [relax/relax#142]

**Comment by bruno12mota** [comment]
How should the user be informed that the change he's making is only applied for that display? I think it would be cool to have some sort of info on the option you just changed in a specific display

**Comment by magalhas** [comment]
No doubts about that. That's a UI/UX issue anyway so we should bring @ivomiguelas into this discussion. I think we could anyway start working out the technical part.

**Comment by bruno12mota** [comment]
Yes, I'm working on that already

**Comment by bruno12mota** [comment]
Also I think the behavior should be, if you change a setting in tablet display for example, it is also applied when viewing in mobile. So it is applied to all smaller views. I think this makes sense
