### ISSUE TITLE
Make should component update functions on components

### ISSUE THREAD

**Issue by bruno12mota** [relax/relax#148]
Since we now have redux working (immutability), it's pretty easy to make shouldComponentUpdate functions. It should be applied everywhere when possible.

**Comment by magalhas** [comment]
Do we need fine grained control over the `shouldComponentUpdate` algorithm or can we implement a magic method that does everything? In this case we could implement a base method on our base `Component` class.

**Comment by magalhas** [comment]
We can also override that method is certain cases.

**Comment by bruno12mota** [comment]
Didn't thought of it, makes sense though, should it check the propTypes object and check if any of them changed? This might bring a great performance boost if it works

**Comment by magalhas** [comment]
I'm not sure if we'll see a big difference since containers that use `connect` already got that type of logic.

**Comment by bruno12mota** [comment]
Would be great if we could make some performance test on it, but will be hard to do so
