### ISSUE TITLE
Remove from tabs after removing page

### ISSUE THREAD

**Issue by bruno12mota** [relax/relax#149]

**Comment by bruno12mota** [comment]
Do the tabs update after removing a page which is displayed in the tabs?

**Comment by magalhas** [comment]
#73e4e08

**Comment by bruno12mota** [comment]
Missing remove from database when removing page

**Comment by bruno12mota** [comment]
Check lib/server/models/page.js there's a commented hook there, uncomment and test it out to complete this task

**Comment by magalhas** [comment]
The task was not well described then. Feel free to do so, I'll be focused on the webpack build and dev env in the next couple of days.



Cumprimentos,
José Magalhães

**Comment by bruno12mota** [comment]
Will do!
