### ISSUE TITLE
Section - Image repeat setting don't work on some modes

### ISSUE THREAD

**Issue by magalhas** [relax/relax#150]
At least `repeat vertically` is not working.

**Comment by bruno12mota** [comment]
All working for me, what does it show for you?

**Comment by magalhas** [comment]
Repeat vertically shows the background vertically only once. But I'll reconfirm and attach a screenshot.

**Comment by bruno12mota** [comment]
I see now why you though it wasn't working. You need to change the horizontal position to 0% and it will show up. I think this can be closed
