### ISSUE TITLE
Comments

### ISSUE THREAD

**Issue by damiandennis** [relax/relax#151]
amazing work btw, I have noticed one major flaw though if you want this to go mainstream. You will need more comments in your code, they are largely lacking.

**Comment by damiandennis** [comment]
just using jsdoc would be a huge improvement.
http://usejsdoc.org/

**Comment by magalhas** [comment]
First thank you for the kind words. Regarding comments I'm more keen of a literate programming approach than JSDOC, though we're completely lacking on in source documentation. Anyway, our intentions are to first go over the top with #53

**Comment by bruno12mota** [comment]
Will be working on the wiki whenever I can, any help would be greatly appreciated

**Comment by bruno12mota** [comment]
Closing this, will address the documentation as soon as possible
