### ISSUE TITLE
date picker option

### ISSUE THREAD

**Issue by bruno12mota** [relax/relax#167]

**Comment by bruno12mota** [comment]
![date picker months](https://cloud.githubusercontent.com/assets/4086031/12421411/20658332-beba-11e5-9dd8-d7f19ed50d23.png)
![date picker years](https://cloud.githubusercontent.com/assets/4086031/12421410/20653d8c-beba-11e5-8e6f-a71942b3c98b.png)
![date picker](https://cloud.githubusercontent.com/assets/4086031/12421412/2069b0b0-beba-11e5-937e-8fc942de180f.png)

my proposal

**Comment by magalhas** [comment]
I like the UI though I've got some considerations regarding UX:
- How does the user know where to transition between the days/month/years view?
- Many times people just want to simply type the date and time in their format. How do we handle this? And how will the pick react to the user input from this point of view?
- Many times hours are optional, having the inputs always visible on all date inputs is not optimal

**Comment by bruno12mota** [comment]
![date picker](https://cloud.githubusercontent.com/assets/4086031/12517273/d997b728-c129-11e5-907b-63af50cc8333.png)

What about something like this? Depending on what has focus it changes the content below

**Comment by magalhas** [comment]
This looks like a better approach though it's still important to be able to parse a date inserted with text. And also how do we define what date format are we using, etc.

**Comment by bruno12mota** [comment]
The date format is specified in another option. Text isn't necessary

**Comment by magalhas** [comment]
As long as the picker recognized text input that's ok for me. What about the time picker? When will it be displayed?

**Comment by bruno12mota** [comment]
Why would it need to recognize text? By time you mean the hours? it should be optional but still didn't go through it

**Comment by magalhas** [comment]
We already discussed this. As a user I want to be able to type a date without having to use the mouse to pick it. It's way better to type "2016/01/20" than having to go through three different select boxes to select the date.

**Comment by bruno12mota** [comment]
You can go through them with tab, I really don't like that solution with a free text input. Takes much longer to input a date in my opinion

**Comment by magalhas** [comment]
As long as you can type. We can handle a / or - as a tab so the user is not forced to use tab. We could also automatically jump to the next field when we detect the input.
