### ISSUE TITLE
ignore getInitialState warning function

### ISSUE THREAD

**Issue by magalhas** [relax/relax#170]
Find a way to suppress this message while in development.

**Comment by bruno12mota** [comment]
I think for this we'd have to fork and change it on the react code itself

**Comment by magalhas** [comment]
There must be a way of doing this in the build process, something for webpack or what not.

**Comment by bruno12mota** [comment]
https://github.com/facebook/react/issues/5545 should we rename it? maybe to "getInitState"?

**Comment by magalhas** [comment]
Well I don't like the idea of having to do a mass search & replace just to get rid of a warning when we're pretty aware of what we're doing but I guess it's a solution to close this.

**Comment by bruno12mota** [comment]
The big advantage is being able to spot other react warnings. Which for now is finding a needel in the middle of those getInitialState warnings. So might be our best soultion

**Comment by magalhas** [comment]
Yeps. Feel free to go for it if you find some time. We'll have to change relax-framework repo. Btw we should rename that repo to "relax-helpers" or something similar.
