### ISSUE TITLE
Error: Reducer "router" returned undefined handling "@@reduxReactRouter/routerDidChange". To ignore an action, you must explicitly return the previous state.

### ISSUE THREAD

**Issue by ZuoweiWang** [relax/relax#175]
Error: Reducer "router" returned undefined handling "@@reduxReactRouter/routerDidChange". To ignore an action, you must explicitly return the previous state.

**Comment by bruno12mota** [comment]
I think that was due to the browser trying to fetch the favicon from the server when none was returned. It should be corrected since it know has a default icon #176

**Comment by bruno12mota** [comment]
Will close for now, if the error persists will re open, thanks!

**Comment by ZuoweiWang** [comment]
@bruno12mota Thanks for your answers...
