### ISSUE TITLE
Implement shadow options

### ISSUE THREAD

**Issue by ivomiguelas** [relax/relax#181]

**Comment by ivomiguelas** [comment]
Development of #164

**Comment by bruno12mota** [comment]
Dependent on #159

**Comment by bruno12mota** [comment]
Just a few notes:

* Text shadow doesn't have a spread property
* Box shadow can be inset
* After adding a shadow shouldn't it appear in some sort of list (similar to the schema filter)
* I think initially there can be only one 'add new shadow' button visible, by clicking it, it adds a new shadow with default values and with the options expanded, this way you can change and see the results on the fly, when you're done you can collapse it

Let me know what you think @ivomiguelas

**Comment by ivomiguelas** [comment]
@bruno12mota Check Zeplin, updated version similar to filters.

**Comment by bruno12mota** [comment]
:+1: that's it!
