### ISSUE TITLE
Implement rounded corners option changes

### ISSUE THREAD

**Issue by ivomiguelas** [relax/relax#182]

**Comment by ivomiguelas** [comment]
Development of #161

**Comment by bruno12mota** [comment]
@ivomiguelas I think it is done, can you review the different states before closing this though? Made a few assumptions on the coloring according to what is selected and active.

**Comment by ivomiguelas** [comment]
@bruno12mota The selected corner(s) is what should appear with the blue highlight. All the rest appear as grey with white being the hover state.

**Comment by bruno12mota** [comment]
But there's one more state than those. There's the 'in use' state. Which can be the center or the four corners, which shows if the sides are all the same or are custom for each one
