### ISSUE TITLE
Demo doesn't work?

### ISSUE THREAD

**Issue by israelidanny** [relax/relax#189]
The demo portal doesn't seem to work.

**Comment by magalhas** [comment]
@israelidanny it looks that it's working fine. What problem are you facing?

**Comment by bruno12mota** [comment]
Will close this for now, demo seems to be running good

**Comment by israelidanny** [comment]
Half the pages are just plain white, and the main page looks like this.
<img width="1392" alt="screen shot 2015-12-01 at 12 51 20 pm" src="https://cloud.githubusercontent.com/assets/1970424/11498790/494aab94-982a-11e5-8c90-c5f9250860ff.png">

**Comment by bruno12mota** [comment]
The public pages rendering isn't final, we've been focusing in the backend, some changes to it might break the public pages. Is the admin area working well for you?

**Comment by bruno12mota** [comment]
Fixed the public page rendering, you can check it out on the demo
