### ISSUE TITLE
Padding NaN

### ISSUE THREAD

**Issue by JoseCMRocha** [relax/relax#190]
When giving different padding to container, if clear the value using backspace, it will appear NaN when all digits are cleared.
Browser: Chrome, Firefox.

![relax](https://cloud.githubusercontent.com/assets/3865634/11468171/b12c9462-974d-11e5-815e-58cbb10a55c2.PNG)

**Comment by bruno12mota** [comment]
Hey! Thanks for letting us know, will have it fixed :+1:
