### ISSUE TITLE
I am having trouble creating new page

### ISSUE THREAD

**Issue by bhavin4ads** [relax/relax#191]
When I try to create a new page , the action is not completed and the wait circle keeps on rolling.
Link:
http://demo.getrelax.io/admin/page/5659b7ba9d7c84154508579e

**Comment by bruno12mota** [comment]
Hey, are you using firefox? I believe there is a bug when using firefox, can you confirm this?

**Comment by bhavin4ads** [comment]
Unhandled promise rejection TypeError: Cannot read property '_id' of null(…)

**Comment by bhavin4ads** [comment]
No I am using chrome

**Comment by bhavin4ads** [comment]
your interface is great. looking forward to it

**Comment by bruno12mota** [comment]
Strange, doesn't happen to me. Can you provide a step by step to replicate the problem?

**Comment by bhavin4ads** [comment]
Sure,
I started the application,
then there is a strip on the top where I think all page list is shown,
I clicked + icon and there it throws this error

**Comment by bruno12mota** [comment]
Maybe you entered an already created slug. Just confirmed that no error message is shown on that case, so that's a bug :+1:

**Comment by bhavin4ads** [comment]
yes that it...

**Comment by bhavin4ads** [comment]
One more thing.
suppose I have added 2 columns.
Then again I click + (add) for adding more elements. (say button bigPlus)
I keep it that way and dont close it

Now I click any one column and a black dot appears on the edges.
On hover it changes to a another + sign for adding more elements to it. (say button smallPlus)

Now there is a small down arrow on this.
If I click on this then button bigPlus also performs same actions in his area as the smallPlus buttons do...

**Comment by bruno12mota** [comment]
The bi plus on the bottom left, is the general elements menu, there you have all the elements visible all the time, you can drag those elements into the canvas.

The small dots that appear in the canvas when you select an element are an inline way of adding elements, and it is based on the selected element, if you have the columns selected you can only add a 'column' element for example

**Comment by bhavin4ads** [comment]
I am talking about expanding and collapsing functionality.
whenever I click on the arrow, it reflects on both elements, general as well as specific.

Thanks

**Comment by bruno12mota** [comment]
Oh, yes that's on purpose actually, the idea is that when your done structuring the page for example and you collapse the structure elements division it will be collapsed everywhere. Don't you agree with this behaviour?

**Comment by bhavin4ads** [comment]
Ohh then its nice
