### ISSUE TITLE
Drag media to another container crashes the page.

### ISSUE THREAD

**Issue by JoseCMRocha** [relax/relax#192]
I´m having a problem dragging media from a container to another container. This causes the page events to crash.

![relax1](https://cloud.githubusercontent.com/assets/3865634/11497837/e3f7ccd0-981b-11e5-88d9-83b655d469a1.PNG)
![relax2](https://cloud.githubusercontent.com/assets/3865634/11497838/e5a60c18-981b-11e5-8346-1109c63f28c4.PNG)

The page test I´m using is this, don´t know if you can access it.
http://demo.getrelax.io/admin/page/565c14ad9d7c8415450857ab

**Comment by bruno12mota** [comment]
This relates to #174 will have it fixed soon. Thanks for reporting! :+1:

**Comment by bruno12mota** [comment]
Fixed and deployed, you can check it again http://demo.getrelax.io/admin/page/565c14ad9d7c8415450857ab :smiley:

**Comment by joseKrocha** [comment]
It was deployed for the demo page? It continuous breaking the events for me.

**Comment by JoseCMRocha** [comment]
It was deployed for the demo page? It continuous breaking the events for me.

**Comment by bruno12mota** [comment]
I misunderstood the bug, I fixed the container into itself one. But noticed the bug you reported is another one, will correct that one as well. Thanks!

**Comment by bruno12mota** [comment]
It is actually a problem with google maps element, will fix it now

**Comment by bruno12mota** [comment]
Deploying now, will tell you when it is done ;)

**Comment by bruno12mota** [comment]
It's live :+1:

**Comment by JoseCMRocha** [comment]
It´s great :+1:
