### ISSUE TITLE
Google Maps Lat and Long

### ISSUE THREAD

**Issue by JoseCMRocha** [relax/relax#193]
In settings if you try to use write lat or long with coma or with dot it will take you to different places.
I think the input text doesn't like the coma.
If you try with input ```type="number"  step="0.01"``` it will accept both comma and dot. But don´t know if this is your desired solution. If yes, i will make the suggestion that the step value should be according the zoom, so if the zoom is high the step will be small and if the zoom is low the step will be bigger. 

This will bring another a small problem cross browser with the css for the buttons that appear on the ```input type="number"``` that you can click to raise or lower the number.

Test pag.
http://demo.getrelax.io/admin/page/565c14ad9d7c8415450857ab

**Comment by bruno12mota** [comment]
I think it should only accept the dot, since it's what comes in the google maps url and what javascript uses for float numbers so, comma shouldn't even be accepted. Will make a way that if you input a comma it is converted to dot automatically
