### ISSUE TITLE
Implement color picker

### ISSUE THREAD

**Issue by ivomiguelas** [relax/relax#194]
Check in Zeplin. Label "styles".

**Comment by bruno12mota** [comment]
Blocked due to radial gradient. Check zeplin comment

**Comment by ivomiguelas** [comment]
Save the states of both gradients and fill when switching between them. Allowing to come back to a previously created gradient after trying a solid color. (While the color picker is open)

**Comment by ivomiguelas** [comment]
On the linear gradient, clicking on the gradient line in the preview, should add new color point.

**Comment by ivomiguelas** [comment]
Check for updates in Zeplin

**Comment by bruno12mota** [comment]
Gradients seem to be closed in terms of ui/ux, I think the last piece remaining is the color collection management

**Comment by bruno12mota** [comment]
I think last thing missing is then the colors management

**Comment by magalhas** [comment]
@ivomiguelas it would be awesome if you could take a look into that in the incoming couple of days.

**Comment by bruno12mota** [comment]
@ivomiguelas color palette management still missing

**Comment by ivomiguelas** [comment]
Check Sketch File
