### ISSUE TITLE
Demo problems on Firefox

### ISSUE THREAD

**Issue by artelse** [relax/relax#196]
Tried the demo on Firefox and pages remain empty with just the spinning icon. In the dashboard at first load the General tab shows the forms, but subsequent tabs all remain empty.

**Comment by bruno12mota** [comment]
Yes it seems to be some error in the client side routing, if some one could pick this one up would be great!

**Comment by artelse** [comment]
FYI: It logs following error: TypeError: e is null common.js:6:13672

**Comment by meshabdullah** [comment]
The problems are still there, demo is not working on firefox, I thought it's currupted demo or outdated until I saw this issue.
