### ISSUE TITLE
install error: need upgrade history v1.13.1 -> v1.16.0

### ISSUE THREAD

**Issue by jicknan** [relax/relax#202]
$ npm install 
npm ERR! Darwin 15.2.0
npm ERR! argv "/usr/local/Cellar/node/4.1.1/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v4.1.1
npm ERR! npm  v2.14.4
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package history@1.16.0 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer react-router@1.0.2 wants history@1.13.x

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/nan/code/relax/npm-debug.log

**Comment by jicknan** [comment]
resolved at https://github.com/rackt/react-router/releases/tag/v1.0.2:

`npm install --save history@1.13.1`

**Comment by bruno12mota** [comment]
Fixed, thanks :+1:
