### ISSUE TITLE
Parallel Shell - Permission Denied

### ISSUE THREAD

**Issue by gRoberts84** [relax/relax#215]
Hey,

When trying to get Relax running on two separate vagrant boxes, I always end up with the same issue where parallel shell fails with permission denied.

In the latest instance, I created an instance of the **weboaks/mean** box and simply installed `build-essential` before cloning Relax and running `npm install`

When running `npm run dev` I get the following:

	vagrant@relax:/var/www/relax$ npm run dev

	> relax@0.0.0 dev /var/www/relax
	> parallelshell 'npm run webpackServer' 'npm run watchServer'

	sh: 1: parallelshell: Permission denied

	npm ERR! Linux 3.16.0-4-amd64
	npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "dev"
	npm ERR! node v5.6.0
	npm ERR! npm  v3.6.0
	npm ERR! code ELIFECYCLE
	npm ERR! relax@0.0.0 dev: `parallelshell 'npm run webpackServer' 'npm run watchServer'`
	npm ERR! Exit status 126
	npm ERR! 
	npm ERR! Failed at the relax@0.0.0 dev script 'parallelshell 'npm run webpackServer' 'npm run watchServer''.
	npm ERR! Make sure you have the latest version of node.js and npm installed.
	npm ERR! If you do, this is most likely a problem with the relax package,
	npm ERR! not with npm itself.
	npm ERR! Tell the author that this fails on your system:
	npm ERR!     parallelshell 'npm run webpackServer' 'npm run watchServer'
	npm ERR! You can get information on how to open an issue for this project with:
	npm ERR!     npm bugs relax
	npm ERR! Or if that isn't available, you can get their info via:
	npm ERR!     npm owner ls relax
	npm ERR! There is likely additional logging output above.

	npm ERR! Please include the following file with any support request:
	npm ERR!     /var/www/relax/npm-debug.log

Running with `sudo` hasn't made any difference either.

When running `npm start` I get something slightly different but ultimately the same issue.

	vagrant@relax:/var/www/relax$ npm start

	> relax@0.0.0 start /var/www/relax
	> NODE_ENV=production ./node_modules/.bin/babel-node app

	sh: 1: ./node_modules/.bin/babel-node: Permission denied

	npm ERR! Linux 3.16.0-4-amd64
	npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
	npm ERR! node v5.6.0
	npm ERR! npm  v3.6.0
	npm ERR! code ELIFECYCLE
	npm ERR! relax@0.0.0 start: `NODE_ENV=production ./node_modules/.bin/babel-node app`
	npm ERR! Exit status 126
	npm ERR! 
	npm ERR! Failed at the relax@0.0.0 start script 'NODE_ENV=production ./node_modules/.bin/babel-node app'.
	npm ERR! Make sure you have the latest version of node.js and npm installed.
	npm ERR! If you do, this is most likely a problem with the relax package,
	npm ERR! not with npm itself.
	npm ERR! Tell the author that this fails on your system:
	npm ERR!     NODE_ENV=production ./node_modules/.bin/babel-node app
	npm ERR! You can get information on how to open an issue for this project with:
	npm ERR!     npm bugs relax
	npm ERR! Or if that isn't available, you can get their info via:
	npm ERR!     npm owner ls relax
	npm ERR! There is likely additional logging output above.

	npm ERR! Please include the following file with any support request:
	npm ERR!     /var/www/relax/npm-debug.log

Thinking it was potentially an issue with the `npm install` and permissions, I ran `sudo npm install -g` too and that didn't fix anything.

Any suggestions as to what I'm doing wrong?

Thanks

**Comment by magalhas** [comment]
I've never used vagrant before but it looks like that all the bin files linked through `npm install` don't have the +x permission on your system.

I'm not sure on how I can help more unless I try to setup that same environment which I can't right now.

Please let me know if you find more clues.

**Comment by bruno12mota** [comment]
Any news on this?

**Comment by gRoberts84** [comment]
I gave up in the end. :(
