### ISSUE TITLE
How to understand npm script for watchServer

### ISSUE THREAD

**Issue by ejamuh** [relax/relax#221]
Keeps error on windows

> '.' is not recognized as an internal or external command,

Wasted 5 hours on this

**Comment by bruno12mota** [comment]
Hey!

Have you installed dependencies first using `npm install`? Can you provide some more detail?

Thanks!

**Comment by ejamuh** [comment]
for sure!

I was trying to run it On Linux, and it works.

But how do I run this on windows?

the power shell always run errors

**Comment by ejamuh** [comment]
First Error Post Installation

![image](https://cloud.githubusercontent.com/assets/2019630/14592201/59173d42-0546-11e6-8db5-5725bdbccbe2.png)

**Comment by ejamuh** [comment]
Then I install eslint 2.4.0, and it seems working

![image](https://cloud.githubusercontent.com/assets/2019630/14592249/c486c6ba-0546-11e6-89fa-2580c6e9666a.png)

**Comment by ejamuh** [comment]
As soon as I hit npm run dev, this error came again

![image](https://cloud.githubusercontent.com/assets/2019630/14592259/dd743c48-0546-11e6-9dc7-054f2ed7c6ed.png)

**Comment by ejamuh** [comment]
So I try another runner, which is better-npm-run. But it keeps error.

I think the problem is with the argument after '-x', what is that actually?

![image](https://cloud.githubusercontent.com/assets/2019630/14592391/2c2be9c0-0548-11e6-81c9-e4e9ad4133a6.png)

**Comment by ejamuh** [comment]
Finally, it works by running this command.

![image](https://cloud.githubusercontent.com/assets/2019630/14592449/e5c9d69e-0548-11e6-9a18-181ceb77d8ff.png)


I quit using nodemon. But..

another error come again. fuhh


![image](https://cloud.githubusercontent.com/assets/2019630/14592455/fe8f7bca-0548-11e6-9822-50ca320e26da.png)

**Comment by ejamuh** [comment]
I forgot to setup the proper MongoDB URL connection, indeed

**Comment by ejamuh** [comment]
{
  "name": "relax",
  "version": "0.0.0",
  "description": "New generation CMS on top of React and Node.js",
  "license": "GPL-3.0",
  "repository": {
    "type": "git",
    "url": "https://github.com/relax/relax.git"
  },
  "scripts": {
    "build": "NODE_ENV=production ./node_modules/.bin/webpack --output-public-path /public/js/ && cp -r assets/images/* public/images",
    "start": "NODE_ENV=production ./node_modules/.bin/babel-node app",
    "dev": "./node_modules/.bin/parallelshell 'npm run webpackServer' 'npm run watchServer'",
    "watchServer": "./node_modules/.bin/nodemon -e js,jsx,json -w app.js -w lib -i lib/client -x \"./node_modules/webpack/bin/webpack.js --config ./webpack/webpack.node.config.js --progress && node build/app\"",
    "webpackServer": "node_modules/.bin/webpack-dev-server --config ./webpack/webpack.browser.config.js --inline --hot --progress --display-error-details",
    "lint": "node_modules/.bin/eslint lib/** --quiet",
    "cmd1": "better-npm-run cmd1",
    "cmd2": "better-npm-run cmd2",
    "cmd3": "concurrent --kill-others \"npm run cmd1\" \"npm run cmd2\""
  },
  "betterScripts": {
    "cmd1": {
      "command": "webpack --config ./webpack/webpack.node.config.js --progress && node build/app",
      "env": {
        "NODE_ENV": "development"
      }
    },
    "cmd2": {
      "command": "webpack-dev-server --config ./webpack/webpack.browser.config.js --inline --hot --progress --display-error-details",
      "env": {
        "NODE_ENV": "development"
      }
    }
  },
  "dependencies": {
    "babel-polyfill": "^6.3.14",
    "body-parser": "^1.13.3",
    "classnames": "^2.1.3",
    "colr": "^1.2.2",
    "connect-mongo": "^0.8.2",
    "dropzone": "git://github.com/relax/dropzone.git",
    "eslint": "^2.4.0",
    "express": "^4.13.3",
    "express-graphql": "^0.4.0",
    "express-session": "^1.11.3",
    "file-size": "^1.0.0",
    "graphql": "^0.4.7",
    "history": "1.17.0",
    "hoist-non-react-statics": "^1.0.3",
    "invariant": "^2.2.0",
    "js-md5": "^0.3.0",
    "kerberos": "0.0.17",
    "keymaster": "git://github.com/relax/keymaster.git",
    "lodash.clone": "^3.0.3",
    "lodash.clonedeep": "^3.0.2",
    "lodash.debounce": "^3.1.1",
    "lodash.filter": "^3.1.1",
    "lodash.find": "^3.2.1",
    "lodash.findindex": "^4.2.0",
    "lodash.foreach": "^3.0.3",
    "lodash.merge": "^3.3.2",
    "lodash.omit": "^3.1.0",
    "lodash.sortby": "^3.1.5",
    "medium-editor": "git://github.com/relax/medium-editor.git",
    "mkdirp": "^0.5.1",
    "moment": "^2.10.6",
    "mongoose": "^4.1.12",
    "morgan": "^1.6.1",
    "multer": "^1.0.6",
    "nodemailer": "^1.5.0",
    "passport": "^0.3.0",
    "passport-local": "^1.0.0",
    "passport-local-mongoose": "^3.1.0",
    "q": "^1.4.1",
    "query-string": "^3.0.0",
    "rc": "^1.1.1",
    "react": "^0.14.0",
    "react-colorpicker": "git://github.com/relax/react-colorpicker.git#relay",
    "react-counter": "git://github.com/relax/react-counter.git#relay",
    "react-dom": "^0.14.0",
    "react-dropzone": "^3.2.2",
    "react-gemini-scrollbar": "^2.0.1",
    "react-google-maps": "^4.6.0",
    "react-redux": "^4.4.0",
    "react-router": "^1.0.2",
    "redux": "^3.3.1",
    "redux-combine-actions": "^0.1.2",
    "redux-logger": "^2.0.4",
    "redux-router": "1.0.0-beta5",
    "redux-thunk": "^1.0.0",
    "relate-js": "^0.1.3",
    "relax-fragments": "0.1.1",
    "relax-jss": "0.2.0",
    "rimraf": "^2.4.3",
    "semver": "^5.0.3",
    "serialize-javascript": "^1.1.2",
    "sharp": "^0.12.0",
    "slug": "^0.9.1",
    "soundmanager2": "git://github.com/relax/SoundManager2.git",
    "source-map-support": "^0.4.0",
    "superagent": "^1.6.1",
    "touch": "^1.0.0",
    "velocity-animate": "git://github.com/relax/velocity.git",
    "warning": "^2.1.0",
    "winston": "^2.1.0"
  },
  "devDependencies": {
    "autoprefixer-loader": "^3.1.0",
    "babel-core": "^6.4.5",
    "babel-eslint": "^6.0.0-beta.5",
    "babel-loader": "^6.2.2",
    "babel-plugin-react-transform": "^2.0.0",
    "babel-plugin-transform-decorators-legacy": "^1.3.4",
    "babel-preset-es2015": "^6.3.13",
    "babel-preset-react": "^6.3.13",
    "babel-preset-stage-0": "^6.3.13",
    "concurrently": "^2.0.0",
    "css-loader": "^0.23.1",
    "eslint": "2.2.0",
    "eslint-config-airbnb": "^6.1.0",
    "eslint-plugin-react": "^4.2.2",
    "extract-text-webpack-plugin": "^0.9.1",
    "file-loader": "^0.8.4",
    "json-loader": "^0.5.3",
    "less": "^2.6.0",
    "less-loader": "^2.2.2",
    "nodemon": "^1.8.1",
    "parallelshell": "^2.0.0",
    "react-transform-catch-errors": "^1.0.2",
    "react-transform-hmr": "^1.0.2",
    "redbox-react": "^1.2.0",
    "style-loader": "^0.13.0",
    "url-loader": "^0.5.6",
    "webpack": "^1.12.6",
    "webpack-dev-server": "^1.12.1",
    "webpack-hot-middleware": "^2.5.0"
  },
  "apps": [
    {
      "name": "relax",
      "script": "index.js",
      "instances": 1,
      "exec_mode": "cluster",
      "error_file": "../shared/logs/stderr.log",
      "out_file": "../shared/logs/stdout.log",
      "pid_file": "../shared/pids/pid",
      "merge_logs": true,
      "env": {
        "NODE_ENV": "production"
      }
    }
  ],
  "deploy": {
    "test": {
      "user": "node",
      "host": "178.62.64.146",
      "path": "/home/node/apps/relax",
      "ref": "origin/master",
      "repo": "https://github.com/relax/relax.git",
      "post-deploy": ". /home/node/.nvm/nvm.sh && npm install && npm run build && pm2 startOrGracefulReload package.json --env production"
    }
  }
}


^ this script runs well on windows 8.

Should I pull request this?

**Comment by bruno12mota** [comment]
It must use nodemon, to watch for changes to relaunch the server on development. So although that's working it's not complete. It should also use the binaries from node_modules to not force users install some libraries globally. I'd accept and thank a lot a PR with the same type of build with nodemon that would work on windows 😃

**Comment by jonjaques** [comment]
Trying to get this to work on windows, ran into [this](https://github.com/npm/npm/issues/4040) regarding `./node_modules/.bin/...`.

Will publish findings :smile:

**Comment by bruno12mota** [comment]
I believe this can be closed now
