### ISSUE TITLE
Error: Cannot find module 'helpers/parse-settings'

### ISSUE THREAD

**Issue by ejamuh** [relax/relax#222]
import parseSettings from '**helpers/parse-settings';**
import passport from 'passport';
import path from 'path';
import safeHtmlString from '**helpers/safe-html-string';**

This line always throw an error

"Error: Cannot find module 'helpers/parse-settings'"

**Comment by bruno12mota** [comment]
The module exists https://github.com/relax/relax/blob/master/lib/shared/helpers/parse-settings.js please use:

```bash
npm run dev
```

instead of 

```bash
npm run start
```

since only the dev build is currently working.

**Comment by ejamuh** [comment]
![image](https://cloud.githubusercontent.com/assets/2019630/14590615/9091b6c0-0529-11e6-937e-7b76f1652f2a.png)


I got issues when starting npm run dev on win8

so I create my own simple script 

![image](https://cloud.githubusercontent.com/assets/2019630/14590619/b8d1c3c8-0529-11e6-9019-13514645538f.png)


and the atom file will contains

![image](https://cloud.githubusercontent.com/assets/2019630/14590620/ca04def0-0529-11e6-95df-83e34e5fc887.png)

**Comment by bruno12mota** [comment]
Do you have npm installed in your system? Use a node version manager like nvm. You don't need that tweak to make it work.
