### ISSUE TITLE
Static File Not Found

### ISSUE THREAD

**Issue by ejamuh** [relax/relax#225]
![image](https://cloud.githubusercontent.com/assets/2019630/14592674/829702f6-054b-11e6-8709-9bcd499eec90.png)

**Comment by ejamuh** [comment]
solved


change

lib/server/index.js:41

app.use(express.static('./public'));
to this
app.use(express.static('./assets'));

**Comment by Yaxian** [comment]
@ejamuh 
Thank you, it works for me

**Comment by bruno12mota** [comment]
Files in the assets folder should actually be copied into the public folder on build. Will add that later for the dev build. Thanks!

**Comment by bruno12mota** [comment]
In the dev build it's missing the operation:

```bash
cp -r assets/images/* public/images
```

**Comment by vko-online** [comment]
Shouldn't this be fixed?

**Comment by jonjaques** [comment]
@bruno12mota I believe this can be closed.

**Comment by bruno12mota** [comment]
👍
