### ISSUE TITLE
Starter kit

### ISSUE THREAD

**Issue by vko-online** [relax/relax#234]
Probably we all would love to see starter-kit of this project, just curious what to remove to get it plain/clean app, to make a todo-app for example
Maybe there is a commit of starting point where it transformed to CMS

**Comment by bruno12mota** [comment]
The app has been refactored quite a lot so there's no point in time where you have a stripped down setup I'm afraid. But it's a quite common stack and there are a lot of boilerplates around these

**Comment by vko-online** [comment]
Anyway, would be awesome to have a simple starter.
What about react-native? Can `lib/shared` be reused?

**Comment by jonjaques** [comment]
Just opining here but I think this is really out of scope for this project, at least for right now. 

You want is to be able to have something like `$ relax new my-todo-app`, right?

What would be needed for that to be feasible is for the app to be encapsulated into a `relax-core` module, and then your 'starter' wouldn't have all the core code mixed in with your custom components. This is a worthy goal and not trying to speak for the creators, but there are much higher priorities like finishing the admin and such. 

The alternative would be to just copy the code and stamp out a new copy, but then you lose the ability to get upgrades at the codebase is developed. 

Your best bet for right now is to fork it for a given project, and then `git remote add upstream <this-repo-url>`. That way as new code comes in you can just `git fetch upstream && git merge upstream/master`.

**Comment by jonjaques** [comment]
Despite the long name, this is one of the more feature-complete universal rendering starters: https://github.com/erikras/react-redux-universal-hot-example

I would def recommend that if you just want to get started writing components.

**Comment by vko-online** [comment]
It's not tight coupled with relax-core imho
except `lib/shared/screens/admin/*`, really hard to cleanup

**Comment by bruno12mota** [comment]
@vko-online I think what you want is completely out of scope for Relax
