### ISSUE TITLE
Path Error ?

### ISSUE THREAD

**Issue by sagomm** [relax/relax#238]
I have install relax on my 32-bit debian8 os , But i get too many error while i  run `$npm run dev`, Unfortunately  , i can't fix those error . here are part of my message , may anybody help me out ? 

### after $npm run dev

> relax@0.0.0 dev /root/Desktop/relax-master
> parallelshell "npm run webpackServer" "npm run watchServer"

> relax@0.0.0 watchServer /root/Desktop/relax-master
> nodemon -e js,jsx,json -w app.js -w lib -i lib/client -x "webpack --config ./webpack/webpack.node.config.js && npm run startDev"

> relax@0.0.0 webpackServer /root/Desktop/relax-master
> webpack-dev-server --config ./webpack/webpack.browser.config.js --inline --hot --quiet --display-error-details

[nodemon] 1.9.2
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: app.js /root/Desktop/relax-master/lib/**/*
[nodemon] starting `webpack --config ./webpack/webpack.node.config.js && npm run startDev`
http://localhost:8181/
webpack result is served from http://localhost:8181/js/
content is served from http://localhost:8080
Hash: 470e2945d7f81e5afff9
Version: webpack 1.13.0
Time: 61317ms
     Asset     Size  Chunks             Chunk Names
    app.js  3.04 MB       0  [emitted]  main
app.js.map  2.45 MB       0  [emitted]  main
 [981] ./lib/server ^\.\/.*$ 10.8 kB {0} [built]
    + 988 hidden modules

WARNING in ./lib/server/migrate.js
Critical dependencies:
37:18-64 the request of a dependency is an expression
 @ ./lib/server/migrate.js 37:18-64

ERROR in ./lib/server/shared/helpers/get-unique-slug.js
Module not found: Error: Cannot resolve module 'slug' in /root/Desktop/relax-master/lib/server/shared/helpers
 @ ./lib/server/shared/helpers/get-unique-slug.js 37:12-27

ERROR in Cannot find module 'normalize-url'
 @ ./lib/shared/screens/auth/index.jsx 31:13-35

ERROR in Cannot find module 'normalize-url'
 @ ./lib/shared/screens/auth/index.jsx 23:0-32

ERROR in Cannot find module 'normalize-url'
 @ ./lib/shared/screens/auth/index.jsx 25:0-35

ERROR in Cannot find module 'normalize-url'
 @ ./lib/shared/screens/admin/screens/menus/components/menu.jsx 43:12-34

ERROR in Cannot find module 'normalize-url'
 @ ./lib/shared/screens/admin/screens/menus/components/content.jsx 27:15-40

ERROR in Cannot find module 'normalize-url'
 @ ./lib/shared/screens/admin/screens/media/components/menu.jsx 47:12-34

### the end part of my msg

ERROR in Cannot find module 'normalize-url'
 @ ./lib/shared/screens/admin/shared/components/media-selector/selected/selected.jsx 37:16-42

> relax@0.0.0 startDev /root/Desktop/relax-master
> node build/app

/root/Desktop/relax-master/build/webpack:/lib/shared/components/dnd/droppable/droppable.jsx:9
import styles from './droppable.less';
^
Error: Cannot find module "./droppable.less"
    at webpackMissingModule (/root/Desktop/relax-master/build/webpack:/lib/shared/components/dnd/droppable/droppable.jsx:9:1)

### then program exit 

npm ERR! Tell the author that this fails on your system:
npm ERR!     node build/app
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs relax
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls relax
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/Desktop/relax-master/npm-debug.log
[nodemon] app crashed - waiting for file changes before starting...

### file exist
I'm sure these file exist which  called 'Module Cannot Find' .
 my npm version is 3.9.0 , my node version is 6.0.0 , my webpack version is 1.13.0

**Comment by bruno12mota** [comment]
Have you run `npm install`? Did it output some error?

**Comment by sagomm** [comment]
@bruno12mota  Sorry, I foget it . I install ralex again ,here is the msg :

### after npm install 

root@monkey-w:~/Desktop/relax-master# npm install
npm WARN deprecated autoprefixer-loader@3.2.0: Please use postcss-loader instead of autoprefixer-loader

> buffertools@2.1.4 install /root/Desktop/relax-master/node_modules/buffertools
> node-gyp rebuild

make: Entering directory '/root/Desktop/relax-master/node_modules/buffertools/build'
  CXX(target) Release/obj.target/buffertools/buffertools.o
./Release/.deps/Release/obj.target/buffertools/buffertools.o.d.raw { dev: 2056,
  mode: 33188,
  nlink: 1,
  uid: 0,
  gid: 0,
  rdev: 0,
  blksize: 4096,
  ino: 11141182,
  size: 514,
  blocks: 8,
  atime: 2016-05-09T16:43:09.557Z,
  mtime: 2016-05-09T16:43:09.557Z,
  ctime: 2016-05-09T16:43:09.840Z,
  birthtime: 2016-05-09T16:43:09.840Z }
  SOLINK_MODULE(target) Release/obj.target/buffertools.node
  COPY Release/buffertools.node
make: Leaving directory '/root/Desktop/relax-master/node_modules/buffertools/build'

> kerberos@0.0.17 install /root/Desktop/relax-master/node_modules/kerberos
> (node-gyp rebuild) || (exit 0)

make: Entering directory '/root/Desktop/relax-master/node_modules/kerberos/build'
  CXX(target) Release/obj.target/kerberos/lib/kerberos.o
In file included from ../lib/kerberos.cc:1:0:
../lib/kerberos.h:5:27: fatal error: gssapi/gssapi.h: No such file or directory
compilation terminated.
kerberos.target.mk:90: recipe for target 'Release/obj.target/kerberos/lib/kerberos.o' failed
make: *** [Release/obj.target/kerberos/lib/kerberos.o] Error 1
make: Leaving directory '/root/Desktop/relax-master/node_modules/kerberos/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Linux 4.3.0-kali1-686-pae
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /root/Desktop/relax-master/node_modules/kerberos
gyp ERR! node -v v6.0.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 

> sharp@0.12.2 install /root/Desktop/relax-master/node_modules/sharp
> node-gyp rebuild

make: Entering directory '/root/Desktop/relax-master/node_modules/sharp/build'
  CXX(target) Release/obj.target/sharp/src/common.o
./Release/.deps/Release/obj.target/sharp/src/common.o.d.raw { dev: 2056,
  mode: 33188,
  nlink: 1,
  uid: 0,
  gid: 0,
  rdev: 0,
  blksize: 4096,
  ino: 11141217,
  size: 72,
  blocks: 8,
  atime: 2016-05-09T16:43:18.557Z,
  mtime: 2016-05-09T16:43:18.557Z,
  ctime: 2016-05-09T16:43:18.116Z,
  birthtime: 2016-05-09T16:43:18.116Z }
  CXX(target) Release/obj.target/sharp/src/metadata.o
./Release/.deps/Release/obj.target/sharp/src/metadata.o.d.raw { dev: 2056,
  mode: 33188,
  nlink: 1,
  uid: 0,
  gid: 0,
  rdev: 0,
  blksize: 4096,
  ino: 11141217,
  size: 1334,
  blocks: 8,
  atime: 2016-05-09T16:43:20.557Z,
  mtime: 2016-05-09T16:43:20.557Z,
  ctime: 2016-05-09T16:43:20.208Z,
  birthtime: 2016-05-09T16:43:20.208Z }
  CXX(target) Release/obj.target/sharp/src/operations.o
./Release/.deps/Release/obj.target/sharp/src/operations.o.d.raw { dev: 2056,
  mode: 33188,
  nlink: 1,
  uid: 0,
  gid: 0,
  rdev: 0,
  blksize: 4096,
  ino: 11141217,
  size: 103,
  blocks: 8,
  atime: 2016-05-09T16:43:20.557Z,
  mtime: 2016-05-09T16:43:20.557Z,
  ctime: 2016-05-09T16:43:20.768Z,
  birthtime: 2016-05-09T16:43:20.768Z }
  CXX(target) Release/obj.target/sharp/src/pipeline.o
./Release/.deps/Release/obj.target/sharp/src/pipeline.o.d.raw { dev: 2056,
  mode: 33188,
  nlink: 1,
  uid: 0,
  gid: 0,
  rdev: 0,
  blksize: 4096,
  ino: 11141217,
  size: 1351,
  blocks: 8,
  atime: 2016-05-09T16:43:23.557Z,
  mtime: 2016-05-09T16:43:23.557Z,
  ctime: 2016-05-09T16:43:23.844Z,
  birthtime: 2016-05-09T16:43:23.844Z }
  CXX(target) Release/obj.target/sharp/src/sharp.o
./Release/.deps/Release/obj.target/sharp/src/sharp.o.d.raw { dev: 2056,
  mode: 33188,
  nlink: 1,
  uid: 0,
  gid: 0,
  rdev: 0,
  blksize: 4096,
  ino: 11141217,
  size: 1365,
  blocks: 8,
  atime: 2016-05-09T16:43:25.557Z,
  mtime: 2016-05-09T16:43:25.557Z,
  ctime: 2016-05-09T16:43:25.292Z,
  birthtime: 2016-05-09T16:43:25.292Z }
  CXX(target) Release/obj.target/sharp/src/utilities.o
./Release/.deps/Release/obj.target/sharp/src/utilities.o.d.raw { dev: 2056,
  mode: 33188,
  nlink: 1,
  uid: 0,
  gid: 0,
  rdev: 0,
  blksize: 4096,
  ino: 11141217,
  size: 1357,
  blocks: 8,
  atime: 2016-05-09T16:43:27.557Z,
  mtime: 2016-05-09T16:43:27.557Z,
  ctime: 2016-05-09T16:43:27.016Z,
  birthtime: 2016-05-09T16:43:27.016Z }
  SOLINK_MODULE(target) Release/obj.target/sharp.node
  COPY Release/sharp.node
  TOUCH Release/obj.target/win_copy_dlls.stamp
Release/obj.target/win_copy_dlls.stamp { dev: 2056,
  mode: 33188,
  nlink: 1,
  uid: 0,
  gid: 0,
  rdev: 0,
  blksize: 4096,
  ino: 11141233,
  size: 0,
  blocks: 0,
  atime: 2016-05-09T16:43:27.557Z,
  mtime: 2016-05-09T16:43:27.557Z,
  ctime: 2016-05-09T16:43:27.348Z,
  birthtime: 2016-05-09T16:43:27.348Z }
make: Leaving directory '/root/Desktop/relax-master/node_modules/sharp/build'

> unicode@0.6.1 postinstall /root/Desktop/relax-master/node_modules/unicode
> node install.js

try to read file /usr/share/unicode/UnicodeData.txt …
parsing …
saving data as Cc.js …
saving data as Zs.js …
saving data as Po.js …
saving data as Sc.js …
saving data as Ps.js …
saving data as Pe.js …
saving data as Sm.js …
saving data as Pd.js …
saving data as Nd.js …
saving data as Lu.js …
saving data as Sk.js …
saving data as Pc.js …
saving data as Ll.js …
saving data as So.js …
saving data as Lo.js …
saving data as Pi.js …
saving data as Cf.js …
saving data as No.js …
saving data as Pf.js …
saving data as Lt.js …
saving data as Lm.js …
saving data as Mn.js …
saving data as Me.js …
saving data as Mc.js …
saving data as Nl.js …
saving data as Zl.js …
saving data as Zp.js …
saving data as Cs.js …
saving data as Co.js …
done.

> history@1.17.0 postinstall /root/Desktop/relax-master/node_modules/history
> node ./npm-scripts/postinstall.js


> react-router@1.0.3 postinstall /root/Desktop/relax-master/node_modules/react-router
> node ./npm-scripts/postinstall.js

relax@0.0.0 /root/Desktop/relax-master
├─┬ autoprefixer-loader@3.2.0 
│ ├─┬ autoprefixer@6.3.6 

.......

### after npm start

root@monkey-w:~/Desktop/relax-master# npm start

> relax@0.0.0 start /root/Desktop/relax-master
> cross-env NODE_ENV=production node build/app

module.js:440
    throw err;
    ^

Error: Cannot find module '/root/Desktop/relax-master/build/app'
    at Function.Module._resolveFilename (module.js:438:15)
    at Function.Module._load (module.js:386:25)
    at Function.Module.runMain (module.js:575:10)
    at startup (node.js:159:18)
    at node.js:444:3

npm ERR! Linux 4.3.0-kali1-686-pae
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v6.0.0
npm ERR! npm  v3.9.0
npm ERR! code ELIFECYCLE
npm ERR! relax@0.0.0 start: `cross-env NODE_ENV=production node build/app`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the relax@0.0.0 start script 'cross-env NODE_ENV=production node build/app'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the relax package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cross-env NODE_ENV=production node build/app
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs relax
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls relax
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/Desktop/relax-master/npm-debug.log


That is all the error log , thanks for you helo :)
