### ISSUE TITLE
ADD COLOR TO PALETTE

### ISSUE THREAD

**Issue by SohamBadheka** [relax/relax#239]
Not able to redirect to the 'colors' page after adding a color, sometimes. The color is being added to the list but not redirecting after adding and the modal is not being closed sometimes !

**Comment by bruno12mota** [comment]
Hey @SohamBadheka does that occur on the master branch or in the demo?

**Comment by SohamBadheka** [comment]
That was in a demo link !

**Comment by bruno12mota** [comment]
The demos is really outdated from the master branch. So the issue shouldn't be there already.

**Comment by SohamBadheka** [comment]
Kudos, good work man !
