### ISSUE TITLE
Installation procedure not very clear

### ISSUE THREAD

**Issue by eduardomart** [relax/relax#241]
As most projects spawning from node.js these days, the documentation is not clear. Sure it makes sense for the makers of this thing but I couldn't get this thing running. RM -RF relax

**Comment by bruno12mota** [comment]
Charming! If you note on the readme, Relax is still not in beta, when it does there will be documentation and a guide to how to install it. Also since this is an open source project you can always contribute to help the project and `rm -rf bad-attitude`
