### ISSUE TITLE
Use bluebird instead of q

### ISSUE THREAD

**Issue by andyhu** [relax/relax#250]
Hi, first thanks for such an amazing project, I love the idea of combining all those cool technologies together. However there is a very old module, `q`. IMO `bluebird` has much better performance, see performance benchmark below:
http://bluebirdjs.com/docs/benchmarks.html
Is it possible to switch to use bluebird?

**Comment by magalhas** [comment]
Hi. We're open to use Bluebird though I'd rather see us using native promises over any lib, I guess they're implemented all over the place as of now.

I'm not sure if we're using anything from A+ spec that requires us to stick to Q/Bluebird or any other Promises library.

**Comment by andyhu** [comment]
Hi, actually `bluebird` is much faster and more feature rich than the native one. I'm not sure if the performance is an important consideration though.

**Comment by magalhas** [comment]
I did a quick search through the project and there are only 9 q imports all over the project. Would you be willing to create a PR?

You could also switch to async/await syntax wherever missing :)

**Comment by andyhu** [comment]
Done!

**Comment by bruno12mota** [comment]
Awesome! Thanks 😃
