### ISSUE TITLE
"Not found" displayed when accessing relax as a non-admin

### ISSUE THREAD

**Issue by isko-algorithm** [relax/relax#254]
How do I access the pages I created in admin mode?

**Comment by isko-algorithm** [comment]
I think so. I cloned the repository and the one from master doesn't seem to be working. So right now, only admin panel works?

**Comment by bruno12mota** [comment]
Yes, the non admin part was done for the old demo but still not done since the refactor. Should be pretty simple to make though, probably till the end of this week I'll have that finished :)

**Comment by isko-algorithm** [comment]
oh okay. will be looking forward. thanks!

**Comment by patrickleet** [comment]
Hey, @bruno12mota - first off, relax is looking awesome! Thanks for your work on it!

Was curious if the frontend rendering has been implemented somewhere - on the master branch when I run, I still get "Not found" at the root url.

**Comment by rwatts3** [comment]
Any progress on the homepage Not Found ?

**Comment by bruno12mota** [comment]
@patrickleet @rwatts3 still not developed. Been focusing on some page builder parts first, templates and symbols mainly. Will get to it as soon as I finish with the dynamic list component refactoring.
