### ISSUE TITLE
[npm bugs relax] Can't install module from `npm start`.

### ISSUE THREAD

**Issue by vanloc0301** [relax/relax#255]
I tried to run Relax. Download and run: `npm install`. I was tried with Node 6.2.2 but error, I must reinstall Windows and setup Node.js v4.4.7 LTS. And error in .log like:

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@2.15.8
3 info using node@v4.4.7
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart relax@0.0.0
6 info start relax@0.0.0
7 verbose unsafe-perm in lifecycle true
8 info relax@0.0.0 Failed to exec start script
9 verbose stack Error: relax@0.0.0 start: `cross-env NODE_ENV=production node build/app`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:217:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:827:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid relax@0.0.0
11 verbose cwd D:\Src Web\relax
12 error Windows_NT 10.0.10586
13 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
14 error node v4.4.7
15 error npm  v2.15.8
16 error code ELIFECYCLE
17 error relax@0.0.0 start: `cross-env NODE_ENV=production node build/app`
17 error Exit status 1
18 error Failed at the relax@0.0.0 start script 'cross-env NODE_ENV=production node build/app'.
18 error This is most likely a problem with the relax package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     cross-env NODE_ENV=production node build/app
18 error You can get information on how to open an issue for this project with:
18 error     npm bugs relax
18 error Or if that isn't available, you can get their info via:
18 error
18 error     npm owner ls relax
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]

```

And another problem:

In my friend computer, I run `npm run dev` it show like:

```
http://localhost:8181/
webpack result is served from http://localhost:8181/assets/
content is served from http://localhost:8080
```

I tried navigation to: localhost:8080 or localhost:8181/assets or http://localhost:8080/admin/init.

All link not available.
My .relaxrc.sample(I don't know create .relaxrc from .relaxrc.sample because Windows not accept file not have name) is:

```
{
  "port": 8080,
  "devPort": 8181,
  "db": {
    "uri": "mongodb://localhost/relax"
  }
}

```

**Comment by bruno12mota** [comment]
Hi @vanloc0301!

Using `npm run dev` you need to wait for the webpack build to finish. You'll know when it's ready when the message `debug: Listening at port 8080` shows up on your console.

To use in production you need to run:

```bash
npm install
npm run build
npm start
```

I believe you forgot the run build command.

**Comment by vanloc0301** [comment]
Thanks @bruno12mota . I tried follow your support but it also have error like:

I was run:

npm install
npm run dev (not show any like debug: Listening at port 8080).
npm run build
npm start

You can see image error at here:

![capture](https://cloud.githubusercontent.com/assets/4168981/16502169/3c7d4340-3f37-11e6-96bb-af4cd395ea99.PNG)


And I using Windows 10, so I can't install package sharp, this will affect anything to `relax`?

**Comment by bruno12mota** [comment]
@vanloc0301 not that `npm run dev` might take a while in the first build since nothing is cached yet. As to the production build check if you have a file under `relax/build/app.js` if not your build didn't succeed. Can't help much on windows since I use mac

**Comment by vanloc0301** [comment]
Thanks, @bruno12mota . I will try in Linux.
