### ISSUE TITLE
cant start

### ISSUE THREAD

**Issue by CCCarla** [relax/relax#256]
Mongoose: mpromise (mongoose's default promise library) is deprecated, plug in your own promise library instead: http://mongoosejs.com/docs/promises.html
debug: Listening at port 8080
error: uncaughtException: connect ECONNREFUSED 127.0.0.1:27017 date=Thu Jun 30 2016 09:07:10 GMT-0700 (PDT), pid=538, uid=501, gid=20, cwd=/Users/carla/Downloads/relax-master, execPath=/usr/local/bin/node, version=v4.2.6, argv=[/usr/local/bin/node, /Users/carla/Downloads/relax-master/build/app], rss=343539712, heapTotal=287917920, heapUsed=240324792, loadavg=[2.08056640625, 1.732421875, 1.10009765625], uptime=695, trace=[column=11, file=util.js, function=Object.exports._errnoException, line=870, method=exports._errnoException, native=false, column=20, file=util.js, function=exports._exceptionWithHostPort, line=893, method=_exceptionWithHostPort, native=false, column=14, file=net.js, function=TCPConnectWrap.afterConnect [as oncomplete], line=1063, method=afterConnect [as oncomplete], native=false], stack=[Error: connect ECONNREFUSED 127.0.0.1:27017,     at Object.exports._errnoException (util.js:870:11),     at exports._exceptionWithHostPort (util.js:893:20),     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1063:14)]

Using the OS X 10.11.5 with Node4.2.6

**Comment by bruno12mota** [comment]
Hey @CCCarla do you have mongo installed in your system? Is it using the default 27017 port?
