### ISSUE TITLE
Beginner friendly issues

### ISSUE THREAD

**Issue by alejandronanez** [relax/relax#260]
Hey there, I'm wondering if we have some specific issues _beginner friendly_ for people new to the repo like me.

Thanks!

**Comment by bruno12mota** [comment]
Hey Alejandro! We don't actually, most of the work to be done involves quite some knowledge about the whole code. There is though work to be done around unit tests and browser compatibility checks. These alone would help the project a lot :)

**Comment by alejandronanez** [comment]
Hey Bruno! What browsers are we supporting?

**Comment by bruno12mota** [comment]
The standard: Chrome, Firefox, IE9+ and Safari. There might be some layout issues on firefox for example as I don't check it that often. I use chrome on dev so the others need to be checked.

**Comment by alejandronanez** [comment]
Cool! Thanks @bruno12mota!
