### ISSUE TITLE
CMIS Integration

### ISSUE THREAD

**Issue by ctxlken** [relax/relax#261]
You might want to consider abstracting all CRUD calls and allowing for the Creation, Reading, Updating, Deleting of content to be done by some other CMS backend that already has things like workflow, image rendition generation, full-text indexing, etc. that will just add to your crazy workload.  This way you can arbitrarily replace the CRUD/CMS feature set layer with any CMS that is CMIS-compliant.  Things like Plone, Drupal, Adobe Experience Manager should all work equally well, so you'd be able to use your lovely React front end on top of these proven CMS tools.

**Comment by bruno12mota** [comment]
Hi! Thanks for the feedback! Although that's not our goal with Relax. We want to make an isolated application as much as we can, and that reflects on what we can achieve with it. We don't want to bind it to another CMS as it would only bring problems.
