### ISSUE TITLE
Error: Command failed: git -c core.longpaths=true config --get remote.origin.url

### ISSUE THREAD

**Issue by SmallShrimp** [relax/relax#262]
run npm install after
error message :
npm WARN addRemoteGit Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
npm WARN addRemoteGit
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:202:12)
npm WARN addRemoteGit     at emitTwo (events.js:106:13)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:191:7)
npm WARN addRemoteGit     at maybeClose (internal/child_process.js:852:16)
npm WARN addRemoteGit     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
npm WARN addRemoteGit  git+https://github.com/relax/SoundManager2.git resetting remote D:\AppDatas\node_cache\_git-remotes\git-https-github-com-relax-SoundManager2-git-a8537966 because of error: { Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
npm WARN addRemoteGit
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:202:12)
npm WARN addRemoteGit     at emitTwo (events.js:106:13)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:191:7)
npm WARN addRemoteGit     at maybeClose (internal/child_process.js:852:16)
npm WARN addRemoteGit     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
npm WARN addRemoteGit   killed: false,
npm WARN addRemoteGit   code: 1,
npm WARN addRemoteGit   signal: null,
npm WARN addRemoteGit   cmd: 'git -c core.longpaths=true config --get remote.origin.url' }
do you know the solution?please!

**Comment by bruno12mota** [comment]
Hi! That doesn't seem to be related with Relax. Which npm version are you using?

**Comment by SmallShrimp** [comment]
谢谢你的回复！I have installed successfully！But there are a lot of problems now running the admin！For example, you can't create a page！the error message：error TypeError: Cannot read property 'constructor' of null！Do we have a development document？谢谢！

**Comment by RyanMontalbano** [comment]
I would be willing to write out some documentation if you would like. Im new to these frameworks, but I would like to help in any way that I can.

**Comment by SmallShrimp** [comment]
thanks so match! I know you are very busy! I really want to have a document! I think your mind of the framework is very good.I would like to return to you! I would like to be able to use your code in our project.

**Comment by bruno12mota** [comment]
@SmallShrimp thanks! @RyanMontalbano things might still change a little bit. Also I'll try to make a place to write documentation similar to what I did in http://relax.github.io/relate/
