### ISSUE TITLE
route

### ISSUE THREAD

**Issue by SmallShrimp** [relax/relax#264]
Where this method comes from？
public.js PageContainer.getQueryAndVariables 

**my route code** `<Route path="/" component={Public} onEnter={gaSend}></Route>`
**and my component Public code** `export default class Public extends Component {
    static propTypes = {
        children: PropTypes.node.isRequired
    };

    render() {
        console.log('渲染 shared public');
        return (
            <div className={styles.content}>

                {this.props.children}
            </div>
        );
    }
}`

in the file public.js ,PageContainer.getQueryAndVariables  is undefined 
so where it comes from?please!thanks!

**Comment by bruno12mota** [comment]
Hi, as I previously said the public route is not done since a refactor we've made to use Relate. So it's normal that there are things there that no longer exist.

**Comment by SmallShrimp** [comment]
OK!Thanks!
