### ISSUE TITLE
cannot reload page when admin screens has stateless function

### ISSUE THREAD

**Issue by fov42550564** [relax/relax#265]
for example, I put follow code In lib/shared/screens/admin/components/admin/index.jsx
```js
const Sample = props=>{
    return <div>{props.test}</div>
};
```
...
```js
render () {
    const {previewing, toggleEditing} = this.props;
    return (
      <div className={styles.root}>
        <Sample test="this is a test text" />
        <TopBar previewing={previewing} toggleEditing={toggleEditing} />
        <div className={cx(styles.content, this.state.build && styles.build)} ref='content'>
          <Menu>
            {this.renderMenuContent()}
          </Menu>
          <div className={cx(styles.pageContent, previewing && styles.pagePreviewing)}>
            {this.props.children}
          </div>
          <PageBuilderMenu previewing={previewing} />
        </div>
      </div>
    );
  }
```
in browser fetch http://localhost:8080/admin,  browser will always waiting, but if I delete the line
```js
<Sample test="this is a test text" />
```
will be ok.
I but the same code In login page will be ok
where is the problem?

**Comment by bruno12mota** [comment]
Are you exporting that Sample function? The error is on the server side rendering so the page won't load

**Comment by fov42550564** [comment]
the Sample function is in the same file(in lib/shared/screens/admin/components/admin/index.jsx)

**Comment by fov42550564** [comment]
yes, The error is on the server side rendering, but in client side reload is ok, why?

**Comment by bruno12mota** [comment]
Can't do much without a stack trace, but I believe it's from Relate server side rendering not supporting functional components. try using class instead of a functional component. Anyway it's something to fix on Relate, more specifically https://github.com/relax/relate/blob/master/lib/server/get-data-dependencies.js#L18

**Comment by fov42550564** [comment]
thank you every much! use class is ok
