### ISSUE TITLE
Some issue occured when I run 'npm run build'!

### ISSUE THREAD

**Issue by Zhang-Yida** [relax/relax#266]
When I run 'npm run build' , some issues occured :
> relax@0.0.0 build E:\libs\React CRM Template\relax
> cross-env NODE_ENV=production webpack --config ./webpack/prod/webpack.config.js

Hash: afb341f4a3a693a6c600c72aa211c2a61cb6cdaf
Version: webpack 1.13.1
Child Client side:
    Hash: afb341f4a3a693a6c600
    Version: webpack 1.13.1
    Time: 158ms
       [0] multi admin 28 bytes {3} [built] [1 error]
       [0] multi auth 28 bytes {2} [built] [1 error]
       [0] multi public 28 bytes {1} [built] [1 error]
        + 3 hidden modules

    ERROR in Cannot find module 'core-js/library/fn/symbol/iterator'
     @ multi admin

    ERROR in Cannot find module 'core-js/library/fn/symbol/iterator'
     @ multi auth

    ERROR in Cannot find module 'core-js/library/fn/symbol/iterator'
     @ multi public
Child Server side:
    Hash: c72aa211c2a61cb6cdaf
    Version: webpack 1.13.1
    Time: 42ms
        + 1 hidden modules

    ERROR in Cannot find module 'core-js/library/fn/symbol/iterator'

Anyone else has the same question? Please

**Comment by bruno12mota** [comment]
Hi! Try pulling latest and try again, should be fixed 😄

**Comment by bruno12mota** [comment]
Closing for now, let me know if the error persists
