### ISSUE TITLE
Drag and drop column crash and break the page

### ISSUE THREAD

**Issue by ArnaudValensi** [relax/relax#269]
Hi,
I create a section with 3 column with an image in each. I drag the second column after the third.
The column does not drop. If I click save, the page break and the loader keep spinning when we try to reopen the page.

I broke the demo: http://demo.getrelax.io/admin/pages/57c5564e71eaae1700535c94

Also, I have an important page on my website, how can I revert it?

**Comment by bruno12mota** [comment]
Hey @ArnaudValensi! Thanks for reporting will try to recreate and fix it 🍻
