### ISSUE TITLE
SEO settings

### ISSUE THREAD

**Issue by bruno12mota** [relax/relax#27]
Meta title
Meta description

**Comment by swennemans** [comment]
Check out: https://github.com/nfl/react-helmet

**Comment by bruno12mota** [comment]
Hey! We've actually have something similar in action already on server side:

````
res.locals.header = [
      {
        tag: 'title',
        content: settings.title
      },
      {
        tag: 'link',
        props: {
          rel: 'stylesheet',
          type: 'text/css',
          href: '/css/main.css'
        }
      }
      ...
];
````

There is just missing the matter of changing the title on the backbone routes, and, correct if I'm wrong the meta description per page (will have to add a meta description option on the page settings)

**Comment by magalhas** [comment]
Should we still care with the `description` tag now a days?

**Comment by bruno12mota** [comment]
Should ate least change the title with "siteTitle - pageTitle"
