### ISSUE TITLE
Relax seem non-responsive.

### ISSUE THREAD

**Issue by vanloc0301** [relax/relax#302]
I test with demo version(admin panel) seem it non-responsive.

Have any library or using Bootstrap to do this?

And after export to a website, it will be responsive with bootstrap or ....?

I think to need to add an option like:

Responsive.
     + Using bootstrap: with add class name, support multiple class.
     + Custom CSS, SCSS by user defined.

**Comment by bruno12mota** [comment]
Hey! It is fluid since it adapts to different screen sizes, just not prepared for mobile size screens which involves much more than just fluid layout on an UX perspective. And it's something we're not prioritizing for the beta release

**Comment by vanloc0301** [comment]
I updated my question. I think need to add function to custom style like this.

It will easy to custom page.

How much this project current goes % in the way?

I hope it will appear; I always found the best method to write less code. And I surprise with your project. 

Can you create a check-list future plan and current plan?

And I want talk about method to bind data really awesome. Only drag - drop.

**Comment by bruno12mota** [comment]
We're actually using new GitHub feature https://github.com/relax/relax/projects/1 to keep track of tasks that need to be done. You also check what's missing for the beta release here https://github.com/relax/relax/milestone/1

**Comment by vanloc0301** [comment]
That's great. 

I have a request: Can you add custom style or Bootstrap feature to your task?

Of course, it doesn't need at this time. But I hope it will be a feature in future of Relax. 

Thanks.

**Comment by magalhas** [comment]
@vanloc0301 there's already a way to bind data with drag and drop in Relax!

**Comment by bruno12mota** [comment]
Don't think that's the request @magalhas. @vanloc0301 there'll be a raw element on the page builder with which you can customize freely and add your own set of rules. I'm actually currently working on it.

Also, note that for all other elements you can customize properties per display size. If you switch the display to mobile for example and change an option on the style it will affect only for the mobile display (it might still not be working on the public route but it will)

**Comment by vanloc0301** [comment]
It will easy to build a single page with more custom.
I happy when to know your working on it.

I will close this issues because it resolve my problem.

Thank you very much.

**Comment by bruno12mota** [comment]
No problem 👍
