### ISSUE TITLE
smg?

### ISSUE THREAD

**Issue by xgqfrms-GitHub** [relax/relax#303]
login ?
what's the hell going on?

![x](https://cloud.githubusercontent.com/assets/18028768/18805378/abd2d7e2-823e-11e6-98f4-d590bd4b9456.PNG)

**Comment by xgqfrms-GitHub** [comment]
> Demo credentials:
> 
> user: **demo**
> pass: **demo**

why not give it a Marked label!
https://img.shields.io/badge/Demo%3A-user-brightgreen.svg
**demo**
https://img.shields.io/badge/Demo%3A-password-brightgreen.svg
**demo**

**Comment by bruno12mota** [comment]
Hey, thanks for the suggestion! Will improve this for the beta release. Ps. dunno why the agressiveness

**Comment by xgqfrms-GitHub** [comment]
I awfully sorry for that bad temper!
please forgive me for bad manners!
