### ISSUE TITLE
"Relax isn't yet ready for production" What is missing?

### ISSUE THREAD

**Issue by dmr** [relax/relax#307]
I like relax and like to ask if anybody is using it in production. The first sentence in github states that it shouldn't be used but maybe things changed and nobody updated the readme?

**Comment by bruno12mota** [comment]
Hey @dmr it is still in alpha. You can check what's missing for the beta here https://github.com/relax/relax/milestone/1 still some things to resolve 😄

**Comment by dmr** [comment]
Cool, thank you
