### ISSUE TITLE
Plans for backend-as-a-service

### ISSUE THREAD

**Issue by sedubois** [relax/relax#312]
Are there any plans to provide Relax as a backend-as-a-service once it is released?

[Graph.cool](https://graph.cool/) and [Scaphold.io](https://scaphold.io/#/) are backends-as-a-service, but not CMS. On the other end, there are GraphQL CMS solutions emerging, but not backend-as-a-service.

Very excited to see this project gaining so much interest 😊

**Comment by bruno12mota** [comment]
Hey @sedubois the GraphQL api is exposed so you can use it to make pretty much anything you want. There won't be any difference in the UI for now at least, so if you use it as a backend-as-service only, you'll still have all the other stuff around it such as page building, templates, etc.

**Comment by sedubois** [comment]
I rather meant, offering a hosted backend solution, so that users don't have to deploy that themselves (similar to [graph.cool](https://graph.cool/) or [scaphold.io](https://scaphold.io/). But anyway thanks for the explanation 😊

**Comment by sedubois** [comment]
OK this is answered in your [wiki](https://github.com/relax/relax/wiki#future-plans): 

> In a later phase we'll also provide a Sass where people can buy a server with Relax already installed and setup.
