### ISSUE TITLE
Draft page selectable as Frontpage

### ISSUE THREAD

**Issue by sedubois** [relax/relax#318]
- create a `Homepage` with a Section containing a `Hello world!` TextBox
- don't save the changes, simply navigate back
- go to general settings: `Homepage` is selectable as Frontpage
- click "save changes" in general settings
- navigate to http://localhost:8080/ : after displaying "Loading...", I just get an empty page

I guess there should be a confirmation popup, when navigating out of the Homepage editor, to know if changes should be saved. If not yet saved, Homepage shouldn't be selectable as Frontpage.

Don't know if I should file such issues, or if too early...

**Comment by bruno12mota** [comment]
That's definitely things you should report. Indeed the homepage picker should filter the non published pages.
