### ISSUE TITLE
assets/admin.js:41 : e is not a function

### ISSUE THREAD

**Issue by sedubois** [relax/relax#319]
When clicking on Reset this property for navigation background color.
<img width="1245" alt="1241082a-916a-11e6-959e-12787c0ce3d9" src="https://cloud.githubusercontent.com/assets/4217871/19357727/8169d2c0-917b-11e6-8798-bc019e497eb6.png">

**Comment by bruno12mota** [comment]
I think for the 'Optional' input option (which is the option that shows the label with the checkbox on the side) there is indeed a bug for the revert. Will check it out 👍 

(keep them coming, loving it 😄 )
