### ISSUE TITLE
clicking cog in top right doesn't do anything

### ISSUE THREAD

**Issue by sedubois** [relax/relax#321]
The cog left of "preview"

<img width="311" alt="screen shot 2016-10-13 at 17 36 47" src="https://cloud.githubusercontent.com/assets/4217871/19353337/b5c94664-916b-11e6-8db9-3975ed7ed2b5.png">

And nothing in console.

**Comment by bruno12mota** [comment]
It still doesn't have an action. There's actually an issue for it https://github.com/relax/relax/issues/186. Suggestions are welcome though 😄
