### ISSUE TITLE
npm run dev not working

### ISSUE THREAD

**Issue by sedubois** [relax/relax#322]
I can run the app properly with `npm start`, seeing contents at `http://localhost:8080`, but I get connection refused when using `npm run dev`. The logs however don't seem to show anything wrong:

```shell
> relax@0.0.0 dev XXX/relax
> parallelshell "npm run webpackServer" "npm run watchServer"


> relax@0.0.0 webpackServer XXX/relax
> webpack-dev-server --config ./webpack/dev/webpack.browser.config.js --inline --hot --quiet --display-error-details


> relax@0.0.0 watchServer XXX/relax
> nodemon -e js,jsx,json -w app.js -w lib -i lib/client -x "webpack --config ./webpack/dev/webpack.node.config.js && npm run startDev"

[nodemon] 1.11.0
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: app.js XXX/relax/lib/**/*
[nodemon] starting `webpack --config ./webpack/dev/webpack.node.config.js && npm run startDev`
 http://localhost:8181/
webpack result is served from http://localhost:8181/assets/
content is served from http://localhost:8080
```

**Comment by bruno12mota** [comment]
Hey @sedubois the dev webpack config doesn't have progress flag active so you must wait around 1-2 minutes for the initial build to finish

**Comment by sedubois** [comment]
OK thanks, that's quite long 😄 it might help to document it in the README. Indeed, it works when waiting. And when I do a code change I see the change hot-reloaded after around 5 sec.
