### ISSUE TITLE
setState(...): Cannot update during an existing state transition

### ISSUE THREAD

**Issue by sedubois** [relax/relax#326]
When opening http://localhost:8080/admin/templates/57ff981ac2b8dd657688fad2

`Warning: setState(...): Cannot update during an existing state transition (such as within `render`). Render methods should be a pure function of props and state.`

The stack trace apparently doesn't specify the component:

```
warning	@	warning.js:45
getInternalInstanceReadyForUpdate	@	ReactUpdateQueue.js:40
enqueueSetState	@	ReactUpdateQueue.js:181
ReactComponent.setState	@	ReactComponent.js:65
handleChange	@	index.js:159
proxiedMethod	@	createPrototypeProxy.js:44
dispatch	@	createStore.js:186
(anonymous function)	@	historyMiddleware.js:24
(anonymous function)	@	replaceRoutesMiddleware.js:16
(anonymous function)	@	index.js:208
(anonymous function)	@	index.js:9
(anonymous function)	@	index.js:15
(anonymous function)	@	bindActionCreators.js:7
updateStylesMap	@	canvas.jsx:192
proxiedMethod	@	createPrototypeProxy.js:44
render	@	canvas.jsx:219
tryRender	@	index.js:34
...
```

But I think at least `lib/shared/screens/admin/shared/components/page-builder/elements-menu/elements-menu.jsx` has the issue of using `setState` during render.

**Comment by bruno12mota** [comment]
I'm aware of it, but it is actually what enables a fast "refresh" of the page styles when changing some property. This is the line that does the magic https://github.com/relax/relax/blob/master/lib/shared/screens/admin/shared/components/page-builder/canvas/canvas.jsx#L69 There might be a solution for it, but besides the error output from react there are no implications of doing it this way.

The elements menu I didn't notice and should be looked into 👍

**Comment by bruno12mota** [comment]
Fixed on https://github.com/relax/relax/commit/767bc4f72fb3653a863f2c88ce53e2763bbfa44d
