### ISSUE TITLE
React class name not specified in error logs

### ISSUE THREAD

**Issue by sedubois** [relax/relax#328]
As visible e.g in https://github.com/relax/relax/issues/324, all components are displayed as `BaseComponent` (the parent's name) instead of the child component's name, which makes it quite hard to debug.

**Comment by bruno12mota** [comment]
Yes this is quite annoying, we use a base component in all components that provide some helping shortcuts https://github.com/relax/relax/blob/master/lib/shared/components/component.jsx The displayName should be inherited though.
