### ISSUE TITLE
Preview whole site

### ISSUE THREAD

**Issue by sedubois** [relax/relax#330]
The admin interface provides a Preview functionality on a per-page basis, however it does not allow to preview the page in the context of its template, with working navigation, etc. When building pages, it is therefore necessary to have one browser tab with the admin interface, and one browser tab with the full rendered page one wants to check.

Maybe either the preview should be able to have that functionality (my preferred option), or there should be an extra tab within the admin interface to see the site.

The key advantage being that I wouldn't need to manually refresh the page, to see every time I make changes.

**Comment by sedubois** [comment]
Actually now I see the Homepage within its template 😄 Without having taken any direct action to change this. Maybe it relates to the fact that I got logged out of the site at some point (when encountering bug https://github.com/relax/relax/issues/337)?

**Comment by bruno12mota** [comment]
I think there's some wrong authorizations on some GraphQL queries, so if you're logged in you can see everything but logged out it might be preventing it from loading
