### ISSUE TITLE
Difficult to edit links for container

### ISSUE THREAD

**Issue by sedubois** [relax/relax#331]
Starting from this situation:

<img width="1243" alt="screen shot 2016-10-13 at 19 58 53" src="https://cloud.githubusercontent.com/assets/4217871/19358715/96b61310-917f-11e6-8b47-67fc5c138157.png">

If with my mouse I then move from the right-side Layers menu where Container is highlighted in blue, toward the links menu, the mouse will go over the root Section and will highlight it, even if I don't click (I'm just moving my mouse). In that moment, the canvas is in a strange state where both the Section and the Container are blue:

<img width="1245" alt="screen shot 2016-10-13 at 20 02 46" src="https://cloud.githubusercontent.com/assets/4217871/19358825/1f45abdc-9180-11e6-9ecd-35202bf10b55.png">

Because of this, once I continue my movement and click on the Links menu, I'll be editing the links of the root Section, and not the leaf Container, which is very confusing. I need to carefully navigate my mouse by outside of the window back to the Links menu without going over the Section, to be able to edit the Container Links. Hope you understood what I meant 😉

**Comment by bruno12mota** [comment]
I did, you are not actually linking to any of the target elements. and when you over an element on the layers menu, it also shows the highlight on the canvas, there's just a missing out action on those buttons in the layers menu

**Comment by bruno12mota** [comment]
Neverthless a bug :)
