### ISSUE TITLE
"Drop elements here or click to add"

### ISSUE THREAD

**Issue by sedubois** [relax/relax#332]
That's what the page editor shows:

<img width="1247" alt="screen shot 2016-10-13 at 20 15 11" src="https://cloud.githubusercontent.com/assets/4217871/19359195/c5e24328-9181-11e6-905d-f1c81f6ba839.png">

But I actually have no clue where I could "drop" things from.

**Comment by bruno12mota** [comment]
You can drag an already existing element there. We had some months ago a general button to open  the elements menu but we felt it took longer to create a page that way, so we went with the inline way of adding elements. I think it's the way to go but needs some improvements even if after the beta release

**Comment by sedubois** [comment]
OK it makes more sense, I didn't know of this concept of "publish" (but now it makes sense as I guess other CMSes offer a similar thing). But I didn't see any button to publish?

Anyway right now, e.g my Homepage displays "seeing published version" in top left when editing it, but still when I exit back to main menu, it is shown with an orange dot.

**Comment by bruno12mota** [comment]
Open the "info" tab and the publish button is there (this of course needs to be changed 😄

**Comment by bruno12mota** [comment]
And the label "seeing published version" is not really valid, should be something like "seeing saved version" just to avoid terms confusion

**Comment by sedubois** [comment]
OK it all starts to make more sense 😄 I wonder how I could see the whole page already on http://localhost:8080 though, because I hadn't yet clicked the publish button at any point.

**Comment by bruno12mota** [comment]
I think those checks if it's published or not are not yet done. I have those checks in my mind for before the beta release but it should be opened as issues 😅
