### ISSUE TITLE
Pages are shown with orange sticker even when saved

### ISSUE THREAD

**Issue by sedubois** [relax/relax#333]
I have the feeling that orange is a visual tip to indicate that something was modified but not saved, versus green which would mean it was saved (?), but my pages show an orange dot even after being saved:

<img width="1246" alt="screen shot 2016-10-13 at 20 17 11" src="https://cloud.githubusercontent.com/assets/4217871/19359279/34243ad0-9182-11e6-8430-62e094799165.png">

OTOH, e.g templates don't show any dot:

<img width="1246" alt="screen shot 2016-10-13 at 20 19 38" src="https://cloud.githubusercontent.com/assets/4217871/19359337/76c6496e-9182-11e6-9a98-38d879f1d265.png">

**Comment by bruno12mota** [comment]
orange is for not published, and blue for published. We've discussed this some time ago and we came to the conclusion that it would be better that the save button would also publish the page as well
