### ISSUE TITLE
Hard to guess how to delete a page/template/menu/etc

### ISSUE THREAD

**Issue by sedubois** [relax/relax#334]
The delete page button can be hard to spot for several reasons:
- it is in the right-side "info" menu, which was counter-intuitive to me (it is not an information)
- it is at the very bottom of that menu
- it sits on top of the other menu elements, when the window is too small

<img width="1270" alt="screen shot 2016-10-13 at 20 26 34" src="https://cloud.githubusercontent.com/assets/4217871/19359563/6cabb418-9183-11e6-8e03-2856535144a6.png">

I would ensure that this delete button is accessible from other places, like:
- beside the preview and save buttons in the top right
- outside of the right-side information menu (e.g add an "X" symbol beside the "i" symbol)
- within the left-side menu where all the pages are displayed, showing an X symbol aligned to the right of their name (either always visible or on hover)

Also, the delete menu is incoherent with the experience described above, there the delete menu button is visible directly:

<img width="1246" alt="screen shot 2016-10-13 at 20 32 36" src="https://cloud.githubusercontent.com/assets/4217871/19359774/4fc327cc-9184-11e6-8011-b52e6b857445.png">

I would make it coherent across the different components.

**Comment by bruno12mota** [comment]
Indeed, there are a few incoherencies in terms of ux throught as the UI was made in bits. These are really good suggestions!

**Comment by bruno12mota** [comment]
Fixed 👍
