### ISSUE TITLE
Cannot drag links out of menu

### ISSUE THREAD

**Issue by sedubois** [relax/relax#335]
The menu edition allows to drag elements from left to right, but there doesn't seem to be a way back, to get rid of something I don't want any more 😉 

![untitled](https://cloud.githubusercontent.com/assets/4217871/19359877/bbef5268-9184-11e6-85a1-36e4ec54a875.png)

**Comment by bruno12mota** [comment]
Yup, missing a trash can icon for example where you can drag it into to remove it
