### ISSUE TITLE
Navigation links to undefined

### ISSUE THREAD

**Issue by sedubois** [relax/relax#338]
I managed to create two pages, Home and Discover, both using a template which has a navigation header with links to these two pages. However, they both link to `http://localhost:8080/undefined`.

**Comment by bruno12mota** [comment]
Did you check this on preview mode or on the actual pages?

**Comment by sedubois** [comment]
On the actual pages.

**Comment by bruno12mota** [comment]
Will check it out thanks! 👍

**Comment by bruno12mota** [comment]
Should be fixed now
