### ISSUE TITLE
Custom link domain gets truncated

### ISSUE THREAD

**Issue by sedubois** [relax/relax#339]
When creating a menu and adding a custom link to an external site (e.g https://github.com/relax/relax), the domain gets truncated resulting in linking to http://localhost:8080/relax/relax.

**Comment by sedubois** [comment]
OK now something changed again and for some reason it properly links to the outside domain. Maybe I hadn't clicked save on the template before.

**Comment by sedubois** [comment]
Actually, on mouse over, the link is displayed as https://github.com/relax/relax, but when clicking it, the page simply changes to "Loading" displayed in top left and the URL in browser bar becomes http://localhost:8080/relax/relax.

**Comment by bruno12mota** [comment]
It might be using the Link component from react router instead of a normal html anchor. Will check it out, nice catch 👍
