### ISSUE TITLE
what's the UI lib used?

### ISSUE THREAD

**Issue by t47io** [relax/relax#345]
Glad that I found this awesome RELAX project! Finally can consider migrate my entire Django app to Nodejs with React-based ecosystem!

I noticed you are using Material Icons. What is the UI framework being used? Do you plan to use Material UI? That would be the best!!~~ 

p.s. please label as "question", not an "issue"

**Comment by bruno12mota** [comment]
Hey @t47io thanks! 😄  Actually we're not using material UI or any UI library. I prefer doing everything myself as to prevent a bloat of code I won't use.
