### ISSUE TITLE
Demo site down

### ISSUE THREAD

**Issue by medv** [relax/relax#347]
Just dropping a note here in case you guys haven't noticed, been trying to evaluate it after first seeing it a couple of weeks ago and it's been timing out for a while now. Feel free to delete this issue.

**Comment by sedubois** [comment]
Don't know if it's related, but I also can't get to run it locally? The page loads indefinitely.

**Comment by medv** [comment]
Probably unrelated as http://getrelax.io/ returns 503 Service Unavailable.

**Comment by bruno12mota** [comment]
Yup, seems like mongo container is out of space. Will have it fixed soon, thanks for alerting :)

**Comment by sedubois** [comment]
What about running locally, do you know the problem there?

**Comment by bruno12mota** [comment]
hum, what error do you get?

**Comment by sedubois** [comment]
My bad, I didn't read logs properly: `failed to connect to server [localhost:27017]`. My database wasn't running. I get the surprise every time and every time I forget...

**Comment by bruno12mota** [comment]
You should get mongo running as a service or that will keep happening 😛

**Comment by sedubois** [comment]
Maybe but I'm not developing with Relax at this point, just trying to get it running 😉 Don't want to overload my computer.

**Comment by bruno12mota** [comment]
Demo fixed 😄

**Comment by medv** [comment]
demo dead :( rest in pepperoni
