### ISSUE TITLE
Just curious

### ISSUE THREAD

**Issue by thedonquixotic** [relax/relax#374]
Hey I'm a UX Designer who is thinking about learning a CMS in order to make managing my portfolio a little easier. Drupal and Wordpress seem a little behind the times in tech so I was curious if there were any JS focused React compatible CMSes out there and this came up. Is this still being actively developed?

**Comment by bruno12mota** [comment]
Hey @thedonquixotic! It definitely is and will be, we're releasing the beta in the following 2-3 weeks but you can already test it out and use it. We're also always open to any feedback and/or bug reports 😄
