### ISSUE TITLE
“Uncaught SyntaxError: Unexpected end of input” in demo

### ISSUE THREAD

**Issue by sapegin** [relax/relax#38]
On login page:

![](http://wow.sapegin.me/image/3y2N0h251t1r/Image%202015-10-07%20at%209.22.39%20AM.png)

And big JSON something:

![](http://wow.sapegin.me/image/17382a3i0J3c/Image%202015-10-07%20at%209.23.38%20AM.png)

**Comment by bruno12mota** [comment]
Someone put a script tag in the title setting which was causing that. We'll work out the demo so that it saves to local storage so that this sort of things doesn't happen. Thanks for letting me know!
