### ISSUE TITLE
Yarn Dev Error

### ISSUE THREAD

**Issue by tcasey** [relax/relax#392]
I get this error when running `yarn dev` `$ cross-env NODE_ENV=development node build/app 
error: uncaughtException: Cannot find module './build/Release/sharp.node'`

**Comment by bruno12mota** [comment]
Hey @tcasey what's your node version and OS? Did the dependencies installed correctly?

**Comment by tcasey** [comment]
@bruno12mota 

node version : 4.2.6
OS: macOS Sierra

I did get this error on the initial install and after installing `graceful-fs` it seemed to install fine.

gyp info it worked if it ends with ok
gyp info using node-gyp@3.4.0
gyp info using node@4.2.6 | darwin | x64
gyp info spawn /usr/bin/python
gyp info spawn args [ '/Users/tcasey/.yarn/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/tcasey/development/relax/node_modules/sharp/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/tcasey/.yarn/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/tcasey/.node-gyp/4.2.6/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/tcasey/.node-gyp/4.2.6',
gyp info spawn args   '-Dnode_gyp_dir=/Users/tcasey/.yarn/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/tcasey/development/relax/node_modules/sharp',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
module.js:328
    throw err;
    ^

Error: Cannot find module 'graceful-fs'

**Comment by bruno12mota** [comment]
That's probably an issue with sharp installation but cannot replicate it. Did you check the sharp requisites http://sharp.dimens.io/en/stable/install/?

**Comment by tcasey** [comment]
I just needed to install `graceful-js` and `sharp` by themselves and it worked. Thanks @bruno12mota

**Comment by bruno12mota** [comment]
Wasn't much help but np 😄
