### ISSUE TITLE
use only WOFF fonts

### ISSUE THREAD

**Issue by DanielRuf** [relax/relax#395]
We should use WOFF and WOFF 2 and remove the other old formats to improve the loading times.

http://caniuse.com/#feat=woff
http://caniuse.com/#feat=woff2

**Comment by bruno12mota** [comment]
We use OTF or TTF that ensure a better browser support. We can think in adding the option to upload woff and woff2 as well though 👍

**Comment by DanielRuf** [comment]
WOFF is a container format and contains highly compressed OTF or TTF fonts so this should not be necessary.

Take a look at the charts, you can completely switch to WOFF, the browser support is very good and even IE9 supports it. IE8 should not be supported anymore. Should be safe to ignore such old browser versions.

![screenshot_20170117-084435](https://cloud.githubusercontent.com/assets/827205/22011833/4fc9a464-dc91-11e6-998b-c020323b3ddc.png)

**Comment by DanielRuf** [comment]
Regarding Opera Mini, this browser never did support font-face

http://caniuse.com/#feat=ttf
http://caniuse.com/#feat=fontface

**Comment by DanielRuf** [comment]
Bump.

Shall I provide a PR?
