### ISSUE TITLE
info about used Nucleo icon pack

### ISSUE THREAD

**Issue by DanielRuf** [relax/relax#396]
Unfortunately I could not directly find any hint which pack is used as this seem to be more icons than the free pack and there is no license file which says that we are allowed to directly use these icons.

Do we have to license and buy them?
https://nucleoapp.com/license/

So far I can see 1396 icons in https://github.com/relax/relax/blob/47075ec68479b777d0371fd85b4aac3154b9ee84/lib/shared/styles/icons/nucleo/mini/icons.less

**Comment by bruno12mota** [comment]
Those icons we're using for the Relax UI only. You can't use the nucleo icons on the pages you build unless you buy the license yes.

**Comment by DanielRuf** [comment]
Ok, thanks for the info. So we have to buy the license as they can not be used without buying them even if they are just used for the UI as you normally can't get them for free.

**Comment by bruno12mota** [comment]
Don't buy it, https://github.com/relax/relax/issues/428
