### ISSUE TITLE
Update to concurrently

### ISSUE THREAD

**Issue by searsaw** [relax/relax#401]
In the `dev` script in the `package.json`,[ `parallelshell`](https://github.com/keithamus/parallelshell) is being used. That project is no longer being maintained. I would suggest we change to a tool such as [`concurrently`](https://github.com/kimmobrunfeldt/concurrently). I wanted to make sure this was a direction the project wanted to go before opening up a pull request.

**Comment by bruno12mota** [comment]
Hey @searsaw great suggestion! Feel free to make a PR to change that 👍
