### ISSUE TITLE
Double click to edit doesn't work / Rich Text editor fails

### ISSUE THREAD

**Issue by 4levels** [relax/relax#405]
Editing TextBox elements by double click is not working, neither on a local install as the online demo.  @bruno12mota is already aware and this issue is merely for information only.

As a side note: I'd be happy with an extra icon to trigger edit mode, besides having to double click on an element..

**Comment by 4levels** [comment]
As an additional issue which is pbbly related, the Rich Text interface / editor is not showing up. This happens when defining new content types with properties of the type Rich Text.

**Comment by justindunham** [comment]
I'm seeing the same issue. No console errors, no response to any amount of clicking though.
