### ISSUE TITLE
Pages don't display

### ISSUE THREAD

**Issue by searsaw** [relax/relax#406]
I created a simple homepage with a menu and a button on it. I also created another page, added the same menu and a date to it, and added it to the main menu. When I publish both pages and then try to view the published site, nothing displays. There are no errors in the console.

**Comment by bruno12mota** [comment]
Hey @searsaw I've recently merged a new renderer method for the pages. I haven't updated the frontend part 😅

**Comment by searsaw** [comment]
Ok. Cool! I'm new to the repo. So I'm still working my head around everything. Can you point me in the right direction of where that is? I would be willing to take a look at it and try to get the front-end updated.

**Comment by bruno12mota** [comment]
No worries. You can take a look to https://github.com/relax/relax/blob/master/lib/shared/screens/admin/shared/components/page-builder/canvas/new-canvas.jsx shortly explaining, previously to this refactor we had a traverser function that would traverse the data structure of a page and render the page. The problem with this was that a small change in one element in that data structure would force a new traverse of the tree. What I did was making a PageElement component that connects to the data a specific element needs. A change in that element's data will update only that specific element.

This might be a tricky part to work on 😛

**Comment by 4levels** [comment]
Just to confirm that the same is happing over here: previewing a specific page works, but visiting the site after publishing it yields a blank page..

**Comment by searsaw** [comment]
@bruno12mota when I pull in the most recent code, there still is nothing being displayed on screen.

**Comment by 4levels** [comment]
Over here it works, I ran `yarn`, `yarn build` and `yarn start` (as I
always do after a pull).
