### ISSUE TITLE
Use GraphQL server

### ISSUE THREAD

**Issue by talltyler** [relax/relax#42]
I would suggest moving to GraphQL server https://github.com/RisingStack/graphql-server 
which is still based on MongoDB but as other implementations of GraphQL are put out it gives people options to move because the interface to the data should remain constant.
Also GraphQL fits really nicely with React.

**Comment by bruno12mota** [comment]
We're actually thinking in refactoring it to Relay. It's something that at the time we started this project wasn't still in the picture (not open sourced at least).

It would indeed be a great fit for this project!

**Comment by magalhas** [comment]
What about [graffiti](https://github.com/RisingStack/graffiti)?

**Comment by bruno12mota** [comment]
Sounds good to me. So drop backbone completely and use Relay + Graffiti?

**Comment by magalhas** [comment]
If we drop it completely then we need to change to another routing solution. Or we keep Backbone.Router usage?

**Comment by bruno12mota** [comment]
I'd say keeping the router as is for now with backbone, since it works well to create a common ground with express, we can think of changing later if we want

**Comment by bruno12mota** [comment]
#51
