### ISSUE TITLE
Demo not working

### ISSUE THREAD

**Issue by ximet** [relax/relax#437]
Step to reproduce:
1) In latest Chrome go to site: http://demo.getrelax.io/admin

A.R. 502 Bad Gateway
E.R. Open demo site

**Comment by cpannwitz** [comment]
Project seems abandonded.

**Comment by bruno12mota** [comment]
@cpannwitz project is looking for contributors, not abandoned.

@ximet we'll put it back up again

**Comment by ximet** [comment]
@bruno12mota If need help, I think, I will help you with contribution)

**Comment by bruno12mota** [comment]
Contributions are always welcome! Demo back up 😄
