### ISSUE TITLE
Active or inactive project?

### ISSUE THREAD

**Issue by iamclaytonray** [relax/relax#441]
I noticed that the last commit was 3 months ago but most of the other commits were 6+ months ago. Is this project still active? I was going to submit a bunch of PRs but no need if it's not going anywhere.

**Comment by bruno12mota** [comment]
Hey @iamclaytonray it's active as long there is people contributing to it. I no longer have time for it unfortunately so it's up for grabs by the community

**Comment by iamclaytonray** [comment]
Okay, thanks! I'm going to go ahead and close this issue.
