### ISSUE TITLE
White container on Firefox

### ISSUE THREAD

**Issue by magalhas** [relax/relax#45]
Page builder and other screens don't display anything in Firefox. Didn't take anytime to understand why. Just registering the issue here.

**Comment by pnevyk** [comment]
It's because element with css class `admin-scrollable` is absolutely positioned and so it has zero height in firefox (I don't know why it works in chrome and does not in firefox). When I set `position: relative`, it displays the content, just a little bit moved down. Hope this helps :)

**Comment by pnevyk** [comment]
And the modals are not displayed because element with class `lightbox` has fixed position and has also zero height but I understand this one must have fixed position so the solution should be found out by guys who know CSS better than me
