### ISSUE TITLE
Mozilla Firefox

### ISSUE THREAD

**Issue by podliy16** [relax/relax#46]
Hi.

I've got a weird result in mozilla. Have you tested your app in different browsers? Only I'm getting these blank screens?

![Mozila Firefox](https://cloud.githubusercontent.com/assets/5547419/10341485/9d7190da-6d1d-11e5-9c43-ba3b1597781a.png)

Btw, in chrome everything is ok.

**Comment by magalhas** [comment]
Same as #45. There's a bug in Firefox as of now.

**Comment by bruno12mota** [comment]
@magalhas reported a few minutes back. Check #45
