### ISSUE TITLE
sharp/node-gyp dependency

### ISSUE THREAD

**Issue by ChicagoDave** [relax/relax#47]
With node-gyp being nearly impossible to compile correctly on a Windows system, this dependency makes relax impossible to install. It looks like node-gyp is a dependency of sharp, which is an image-sizing lib. Maybe this isn't super-necessary?

**Comment by bruno12mota** [comment]
Have you tired the steps here: http://sharp.dimens.io/en/stable/install/ ? I use a mac so though for me to try, although the image resizing lib is absolutely necessary, everytime you add an image on page, relax makes sure to load the image with only the needed size

**Comment by ChicagoDave** [comment]
Yes, I followed those instructions. I still get errors:

```
..\src\common.cc(15): fatal error C1189: #error :  Windows 64-bit is currently
unsupported - see http://sharp.dimens.io/page/install#windows [C:\projects\rela
x\node_modules\sharp\build\sharp.vcxproj]
..\src\pipeline.cc(1005): warning C4267: 'argument' : conversion from 'size_t'
to 'uint32_t', possible loss of data [C:\projects\relax\node_modules\sharp\buil
d\sharp.vcxproj]
..\src\metadata.cc(188): warning C4267: 'argument' : conversion from 'size_t' t
o 'uint32_t', possible loss of data [C:\projects\relax\node_modules\sharp\build
\sharp.vcxproj]
..\src\metadata.cc(191): warning C4267: 'argument' : conversion from 'size_t' t
o 'uint32_t', possible loss of data [C:\projects\relax\node_modules\sharp\build
\sharp.vcxproj]
c:\projects\relax\node_modules\sharp\node_modules\nan\nan_new.h(208): warning C
4244: 'argument' : conversion from 'size_t' to 'double', possible loss of data
(..\src\utilities.cc) [C:\projects\relax\node_modules\sharp\build\sharp.vcxproj
]
```

**Comment by bruno12mota** [comment]
Check this issue https://github.com/lovell/sharp/issues/224 they're trying to support it for windows 64-bit, that's something I didn't know about. Hope they launch a fix https://github.com/jcupitt/build-win32/issues/10

**Comment by lovell** [comment]
As well as support for running sharp with the 64-bit node executable on Windows (https://github.com/lovell/sharp/issues/224) we're also hoping to remove the need for a manual vips download and setting of environment variables as part of https://github.com/lovell/sharp/issues/42.

Feel free to subscribe to either/both if you're able to help test.

**Comment by bruno12mota** [comment]
That's great @lovell would make the installation much easier 

:+1:

**Comment by lovell** [comment]
It's probably worth clarifying here that `sharp` does work on 64-bit Windows but currently only when using the 32-bit x86 Node executable.

@ChicagoDave Please aim your constructive suggestions and feedback about `node-gyp` and Windows in the general direction of https://github.com/nodejs/node-gyp/issues/629

@bruno12mota Almost 1k :star: :tada: congrats!

**Comment by bruno12mota** [comment]
@lovell thanks so much, it's been quite overwhelming in a good way :)

**Comment by lovell** [comment]
The forthcoming v0.12.0 release of `sharp` will work with 64-bit `node.exe` on Windows and we'll be dropping support for 32-bit systems in the process.

**Comment by magalhas** [comment]
Awesome news!

**Comment by bruno12mota** [comment]
That's great @lovell, cheers and thank you for letting us know!

**Comment by magalhas** [comment]
It looks like this was covered by @lovell PR #172.
