### ISSUE TITLE
Demo admin panel unresponsive design

### ISSUE THREAD

**Issue by kevinkucharczyk** [relax/relax#48]
The demo admin panel is virtually unusable on mobile (Chrome 45.0.2454.94 on Android 5.1.1). Elements are overlapping each other etc. 
![screenshot_2015-10-07-20-32-30](https://cloud.githubusercontent.com/assets/3127419/10347278/6c7666c0-6d33-11e5-8937-cdf11ca7ef57.png)

**Comment by magalhas** [comment]
Even though you're able to design responsive using the backoffice, the UI is not yet optimised to be used in smaller screens. We'll keep the issue to keep tracking of the feature, but I guess this does not have high priority as of now.

**Comment by safoorsafdar** [comment]
Validation error displaying on other page rather on the same page of auth.

**Comment by bruno12mota** [comment]
@safoorsafdar you're talking about the login right?

**Comment by safoorsafdar** [comment]
yeah login validation errors.

**Comment by safoorsafdar** [comment]
I think need to implement some validation library like jquery validation or parsely js to all forms integration around the whole application.

**Comment by bruno12mota** [comment]
Yup, I'll focus on the refactoring for now #51 as it will depend on it. Will attack this after ;)

**Comment by safoorsafdar** [comment]
what would you prefer Client side or server side validation?

**Comment by safoorsafdar** [comment]
let's create another issues to deal with validation.

**Comment by magalhas** [comment]
I guess both. Though we'll have part of the validations inside GraphQL schemas. The rest will happen inside components, I don't see any "jQuery code" being used on both cases.

**Comment by bruno12mota** [comment]
You can create the issue, just specify what validation you're talking about, don't create a generic one
