### ISSUE TITLE
React Dependencies cannot be satisfied

### ISSUE THREAD

**Issue by theSuess** [relax/relax#60]
I wanted to try out relax and get this dependency error:

    Cannot find module 'react-colorpicker' from 'relax/lib/components/color-palette-picker'

Trying to install it manually gives me this:

    npm ERR! peerinvalid The package react does not satisfy its siblings' peerDependencies requirements!
    npm ERR! peerinvalid Peer express-react-engine@0.4.4 wants react@^0.13.1
    npm ERR! peerinvalid Peer react-colorpicker@0.3.14 wants react@^0.14.0
    npm ERR! peerinvalid Peer react-counter@1.1.0 wants react@^0.14.0
    npm ERR! peerinvalid Peer react-frame-component@0.3.4 wants react@>=0.13.0
    npm ERR! peerinvalid Peer react-gemini-scrollbar@1.1.1 wants react@>=0.12.0 || >=0.13.0-beta
    npm ERR! peerinvalid Peer react-google-maps@2.2.0 wants react@^0.13.0
    npm ERR! peerinvalid Peer relax-framework@0.0.7 wants react@^0.13.2

**Comment by bruno12mota** [comment]
Sorry about that, I'm making a huge refactoring to support react 0.14 + GraphQL + Relay and been updating the git dependencies it has to support 0.14. So unfortunately it broke the build for now, will try to make the refactoring fast but will take at least a few days to a week. 

I'll try to come up with a solution for this, maybe fork the git dependencies to my account and revert the changes for now for the ones on the relax account

**Comment by magalhas** [comment]
Well as of now we could branch all the changes and keep masters for this. It should have done that way in the first place.

**Comment by bruno12mota** [comment]
Will do tomorrow morning then

**Comment by bruno12mota** [comment]
Actually made the corrections today, you can try npm install again, all should go smooth
