### ISSUE TITLE
User hash and salt exposed

### ISSUE THREAD

**Issue by motiooon** [relax/relax#62]
Please see attached image
<img width="1139" alt="screen shot 2015-10-08 at 3 36 35 pm" src="https://cloud.githubusercontent.com/assets/870995/10381769/663dc16e-6dd2-11e5-8044-0e8fa71e2aef.png">

**Comment by magalhas** [comment]
Well spotted. This kind of relates with #51. With GraphQL we'll be able to easily pick the fields we only need in the UI.

I'll keep this open meanwhile.

**Comment by bruno12mota** [comment]
This is fixed for the redux branch, will be merged in about a week
