### ISSUE TITLE
can't delete the last character of inputs

### ISSUE THREAD

**Issue by coolzilj** [relax/relax#70]
Let the screenshot do the talks.
![image](https://cloud.githubusercontent.com/assets/1059327/10386888/bd6be2c4-6e8e-11e5-914f-94fd1039e1f1.png)

**Comment by bruno12mota** [comment]
Indeed, thanks for reporting!

**Comment by bruno12mota** [comment]
This is corrected for the redux branch, will be merged to master in about a week
