### ISSUE TITLE
use webpack for a better dev experience and faster build time

### ISSUE THREAD

**Issue by magalhas** [relax/relax#71]

**Comment by joaosamouco** [comment]
:+1:

Will take a look into it in the upcoming week when I have some free time.

**Comment by magalhas** [comment]
@joaosamouco what's the status on this?

**Comment by magalhas** [comment]
Currently I'm stuck with decorator + export support of Babel@6. There's many issues over their repo, [here's](https://github.com/babel/babel/issues/2702) one related to the topic.
