### ISSUE TITLE
save styles automatically

### ISSUE THREAD

**Issue by magalhas** [relax/relax#75]
It's annoying if you forget to click done you lose all the changes to a style.

**Comment by ivomiguelas2** [comment]
Yes please! Ran into this several times already. We shouldn't even have a done button, save all the time behind the scenes and just include an option to close the window.

**Comment by magalhas** [comment]
Problem is how we handle this. Styles are shared across all the pages, so someone can be editing the exactly same style on another account/page.

**Comment by ivomiguelas2** [comment]
Good point. I think we should still try it out and see how it feels. There are ways in which we can alert to that fact without being too intrusive. I think that risk, while being upfront about it, outweighs the issue of changing all the styles to just close the window and realise they haven't been saved. The other thing is we have a history log of changes, so reverting isn't a huge problem, but closing that window atm means those changes have been lost for ever.

**Comment by magalhas** [comment]
We've got an history log of all the changes to a page though that won't include styles revision as of now.

**Comment by bruno12mota** [comment]
This is done for the redux branch, closing
