### ISSUE TITLE
Allow change to column width on column element

### ISSUE THREAD

**Issue by ivomiguelas** [relax/relax#79]
Column custom widths are only controlled from the parent column component. Allow it for specific columns selected.

**Comment by magalhas** [comment]
@ivomiguelas2 shouldn't we bring up to discussion the ability of being able to resize elements with the mouse by dragging their borders?

**Comment by bruno12mota** [comment]
That would work for the columns only, dragging borders of other elements divs(blocks) wouldn't work

**Comment by magalhas** [comment]
And what about being able to drag other elements border when editing a style? Anyway, doing it for columns to start with would be nice.

**Comment by bruno12mota** [comment]
Don't think so, it's a matter of composition, forcing the user to compose their page right. Although adding that option for the columns would be nice

**Comment by ivomiguelas2** [comment]
I think it would be a great addition. It might be tricky given you don't have the same precision as you would by inputing the values manually, but it's a great way to lay things out quickly without having to always open the settings modal and worry later about the final values. I have some fancy ideas in mind on how to improve the precision and finesse while using the mouse I'd like to experiment with.

**Comment by magalhas** [comment]
Let us know when you have something more concrete :)

**Comment by bruno12mota** [comment]
This is tightly coupled with the columns element, because is this element which knows how many column elements it has and can restrict sizes to ensure the total columns width isn't over 100%, so maybe we can add this as backlog or for the version after the beta release since it's more of a nice to have
