### ISSUE TITLE
Hide not work in the published version

### ISSUE THREAD

**Issue by vlad008** [relax/relax#85]
Do not hide works, in the published version. In the admin panel everything works fine.
![2015-10-15 13 37 07](https://cloud.githubusercontent.com/assets/2377768/10507678/959b2302-733b-11e5-9303-d3c535df92f8.png)
![2015-10-15 13 37 17](https://cloud.githubusercontent.com/assets/2377768/10507679/959e2b56-733b-11e5-9ced-c6860c3131ec.png)

**Comment by bruno12mota** [comment]
You're right just confirmed it. Will correct it, thanks for creating the issue :+1:
