### ISSUE TITLE
page revisions

### ISSUE THREAD

**Issue by bruno12mota** [relax/relax#91]

**Comment by magalhas** [comment]
@bruno12mota revisions output is refactored. We're just missing the restore action and mutation.

**Comment by bruno12mota** [comment]
:+1:

**Comment by magalhas** [comment]
@bruno12mota mutation and action implemented. Check it out

**Comment by bruno12mota** [comment]
@magalhas it is supposed to close the lightbox when you click restore, and it should switch to loading status until the restore completes

**Comment by magalhas** [comment]
It's now closing. Though the loading status I'll leave it for #112
