### ISSUE TITLE
review components

### ISSUE THREAD

**Issue by bruno12mota** [relax/relax#94]
- [x] Button
- [x] Column
- [x] Columns
- [x] Container
- [x] Counter
- [ ] Form
- [x] Gap
- [x] Google maps
- [x] Icon
- [x] Image
- [x] Line divider
- [ ] Menu
- [ ] Music player
- [ ] Schema
- [x] Section
- [x] Text box
- [x] Text Input
- [x] Textarea
- [x] Video

**Comment by magalhas** [comment]
We were relying on `Backbone.Event` on the base `Element` class and on Styles Picker components. I've commented that dependencies out in order to remove `backbone` and `backbone-cortex` from our dependencies.

We'll need to `redux` whatever those events were for :)
