### ISSUE TITLE
GraphQL responses error handling

### ISSUE THREAD

**Issue by magalhas** [relax/relax#97]
This is not trivial because GraphQL error messages are arrays of objects with strings, it's not easy to pinpoint the error to a specific query or mutation when sent many on one request.

I think as of now we should consider any error as a fatal failure and inform the user that the error occurred.

@bruno12mota any thoughts?

**Comment by bruno12mota** [comment]
Think so, usually we send a single mutation request anyway, so it should be ok to assume that

**Comment by magalhas** [comment]
Well there can be errors in multiple queries as well. But we intend to have 0 errors occuring. Btw we also should implement data validations in the GraphQL types.

**Comment by bruno12mota** [comment]
Will close this one, we can open specific ones for each case when applicable for beta version
